version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - noctx
    - unconvert
  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
