// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    public_id, action, actor_type, actor_id, subject_id, target_id, details, ip_address, user_agent, request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAuditEventParams struct {
	PublicID  string
	Action    string
	ActorType string
	ActorID   pgtype.Int8
	SubjectID pgtype.Int8
	TargetID  string
	Details   []byte
	IpAddress *netip.Addr
	UserAgent string
	RequestID string
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.PublicID,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.SubjectID,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}

const deleteExpiredAuditEvents = `-- name: DeleteExpiredAuditEvents :execrows
DELETE FROM audit_events
WHERE id IN (
    SELECT id FROM audit_events
    WHERE created_at < $1::timestamptz
    ORDER BY id
    LIMIT $2
)
`

type DeleteExpiredAuditEventsParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) DeleteExpiredAuditEvents(ctx context.Context, arg DeleteExpiredAuditEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuditEvents, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuditEventCursor = `-- name: GetAuditEventCursor :one
SELECT id FROM audit_events WHERE public_id = $1
`

func (q *Queries) GetAuditEventCursor(ctx context.Context, publicID string) (int64, error) {
	row := q.db.QueryRow(ctx, getAuditEventCursor, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFileAuditTarget = `-- name: GetFileAuditTarget :one
SELECT n.public_id, n.name, l.public_id AS library_public_id, l.name AS library_name,
       l.encryption_mode, l.owner_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.id = $1
`

type GetFileAuditTargetRow struct {
	PublicID        string
	Name            pgtype.Text
	LibraryPublicID string
	LibraryName     string
	EncryptionMode  string
	OwnerID         int64
}

func (q *Queries) GetFileAuditTarget(ctx context.Context, id int64) (GetFileAuditTargetRow, error) {
	row := q.db.QueryRow(ctx, getFileAuditTarget, id)
	var i GetFileAuditTargetRow
	err := row.Scan(
		&i.PublicID,
		&i.Name,
		&i.LibraryPublicID,
		&i.LibraryName,
		&i.EncryptionMode,
		&i.OwnerID,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT e.id, e.public_id, e.action, e.actor_type, e.actor_id, e.target_id, e.details,
       e.ip_address, e.user_agent, e.request_id, e.created_at,
       actor.public_id AS actor_public_id, actor.name AS actor_name, actor.email AS actor_email,
       subject.public_id AS subject_public_id, subject.name AS subject_name, subject.email AS subject_email
FROM audit_events e
LEFT JOIN users actor ON actor.id = e.actor_id
LEFT JOIN users subject ON subject.id = e.subject_id
WHERE ($1::bigint = 0 OR e.id < $1::bigint)
  AND ($2::bigint = 0 OR e.actor_id = $2::bigint OR e.subject_id = $2::bigint)
  AND ($3::text = '' OR e.action = $3::text)
ORDER BY e.id DESC
LIMIT $4
`

type ListAuditEventsParams struct {
	BeforeID  int64
	UserID    int64
	Action    string
	PageLimit int32
}

type ListAuditEventsRow struct {
	ID              int64
	PublicID        string
	Action          string
	ActorType       string
	ActorID         pgtype.Int8
	TargetID        string
	Details         []byte
	IpAddress       *netip.Addr
	UserAgent       string
	RequestID       string
	CreatedAt       pgtype.Timestamptz
	ActorPublicID   pgtype.Text
	ActorName       pgtype.Text
	ActorEmail      pgtype.Text
	SubjectPublicID pgtype.Text
	SubjectName     pgtype.Text
	SubjectEmail    pgtype.Text
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.BeforeID,
		arg.UserID,
		arg.Action,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Action,
			&i.ActorType,
			&i.ActorID,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
			&i.ActorPublicID,
			&i.ActorName,
			&i.ActorEmail,
			&i.SubjectPublicID,
			&i.SubjectName,
			&i.SubjectEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
