// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlobVersionReferences = `-- name: CountBlobVersionReferences :one
SELECT count(*) FROM file_versions WHERE blob_id = $1
`

func (q *Queries) CountBlobVersionReferences(ctx context.Context, blobID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBlobVersionReferences, blobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlob = `-- name: CreateBlob :one
INSERT INTO blobs (
    public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format,
    encrypted_file_key
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format, encrypted_file_key, created_at
`

type CreateBlobParams struct {
	PublicID         string
	LibraryID        int64
	SizeBytes        int64
	CiphertextSha256 []byte
	DedupFingerprint []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
}

func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, createBlob,
		arg.PublicID,
		arg.LibraryID,
		arg.SizeBytes,
		arg.CiphertextSha256,
		arg.DedupFingerprint,
		arg.EncryptionFormat,
		arg.EncryptedFileKey,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.SizeBytes,
		&i.CiphertextSha256,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.CreatedAt,
	)
	return i, err
}

const createBlobLocation = `-- name: CreateBlobLocation :one
INSERT INTO blob_locations (public_id, blob_id, library_id, backend_id, object_key, state)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, public_id, blob_id, library_id, backend_id, object_key, state, verified_at, created_at, updated_at
`

type CreateBlobLocationParams struct {
	PublicID  string
	BlobID    int64
	LibraryID int64
	BackendID int64
	ObjectKey string
}

func (q *Queries) CreateBlobLocation(ctx context.Context, arg CreateBlobLocationParams) (BlobLocation, error) {
	row := q.db.QueryRow(ctx, createBlobLocation,
		arg.PublicID,
		arg.BlobID,
		arg.LibraryID,
		arg.BackendID,
		arg.ObjectKey,
	)
	var i BlobLocation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BlobID,
		&i.LibraryID,
		&i.BackendID,
		&i.ObjectKey,
		&i.State,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileVersion = `-- name: CreateFileVersion :one
INSERT INTO file_versions (
    public_id, node_id, library_id, ordinal, blob_id, size_bytes, content_sha256,
    restored_from_version_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_id, node_id, library_id, ordinal, blob_id, size_bytes, content_sha256, restored_from_version_id, created_at
`

type CreateFileVersionParams struct {
	PublicID              string
	NodeID                int64
	LibraryID             int64
	Ordinal               int64
	BlobID                int64
	SizeBytes             int64
	ContentSha256         []byte
	RestoredFromVersionID pgtype.Int8
}

func (q *Queries) CreateFileVersion(ctx context.Context, arg CreateFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, createFileVersion,
		arg.PublicID,
		arg.NodeID,
		arg.LibraryID,
		arg.Ordinal,
		arg.BlobID,
		arg.SizeBytes,
		arg.ContentSha256,
		arg.RestoredFromVersionID,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.NodeID,
		&i.LibraryID,
		&i.Ordinal,
		&i.BlobID,
		&i.SizeBytes,
		&i.ContentSha256,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const findBlobByDedupFingerprint = `-- name: FindBlobByDedupFingerprint :one
SELECT id, public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format, encrypted_file_key, created_at FROM blobs
WHERE library_id = $1 AND dedup_fingerprint = $2
`

type FindBlobByDedupFingerprintParams struct {
	LibraryID        int64
	DedupFingerprint []byte
}

func (q *Queries) FindBlobByDedupFingerprint(ctx context.Context, arg FindBlobByDedupFingerprintParams) (Blob, error) {
	row := q.db.QueryRow(ctx, findBlobByDedupFingerprint, arg.LibraryID, arg.DedupFingerprint)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.SizeBytes,
		&i.CiphertextSha256,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailableBlobLocation = `-- name: GetAvailableBlobLocation :one
SELECT id, public_id, blob_id, library_id, backend_id, object_key, state, verified_at, created_at, updated_at FROM blob_locations
WHERE blob_id = $1 AND state = 'available'
`

func (q *Queries) GetAvailableBlobLocation(ctx context.Context, blobID int64) (BlobLocation, error) {
	row := q.db.QueryRow(ctx, getAvailableBlobLocation, blobID)
	var i BlobLocation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BlobID,
		&i.LibraryID,
		&i.BackendID,
		&i.ObjectKey,
		&i.State,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBlobLocationAvailable = `-- name: MarkBlobLocationAvailable :one
UPDATE blob_locations
SET state = 'available', verified_at = now(), updated_at = now()
WHERE id = $1 AND state = 'pending'
RETURNING id, public_id, blob_id, library_id, backend_id, object_key, state, verified_at, created_at, updated_at
`

func (q *Queries) MarkBlobLocationAvailable(ctx context.Context, id int64) (BlobLocation, error) {
	row := q.db.QueryRow(ctx, markBlobLocationAvailable, id)
	var i BlobLocation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BlobID,
		&i.LibraryID,
		&i.BackendID,
		&i.ObjectKey,
		&i.State,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
