// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encryption.sql

package db

import (
	"context"
)

const createUserKeyBundle = `-- name: CreateUserKeyBundle :one
INSERT INTO user_key_bundles (
    user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key,
    recovery_encrypted_master_key, master_encrypted_recovery_key
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision
`

type CreateUserKeyBundleParams struct {
	UserID                     int64
	FormatVersion              int32
	KdfSalt                    []byte
	KdfParameters              []byte
	EncryptedMasterKey         []byte
	RecoveryEncryptedMasterKey []byte
	MasterEncryptedRecoveryKey []byte
}

func (q *Queries) CreateUserKeyBundle(ctx context.Context, arg CreateUserKeyBundleParams) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, createUserKeyBundle,
		arg.UserID,
		arg.FormatVersion,
		arg.KdfSalt,
		arg.KdfParameters,
		arg.EncryptedMasterKey,
		arg.RecoveryEncryptedMasterKey,
		arg.MasterEncryptedRecoveryKey,
	)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
	)
	return i, err
}

const getUserKeyBundle = `-- name: GetUserKeyBundle :one
SELECT user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision FROM user_key_bundles WHERE user_id = $1
`

func (q *Queries) GetUserKeyBundle(ctx context.Context, userID int64) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, getUserKeyBundle, userID)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
	)
	return i, err
}

const updateUserKeyBundlePassword = `-- name: UpdateUserKeyBundlePassword :one
UPDATE user_key_bundles
SET format_version = $2, kdf_salt = $3, kdf_parameters = $4,
    encrypted_master_key = $5, updated_at = now()
WHERE user_id = $1
RETURNING user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision
`

type UpdateUserKeyBundlePasswordParams struct {
	UserID             int64
	FormatVersion      int32
	KdfSalt            []byte
	KdfParameters      []byte
	EncryptedMasterKey []byte
}

func (q *Queries) UpdateUserKeyBundlePassword(ctx context.Context, arg UpdateUserKeyBundlePasswordParams) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, updateUserKeyBundlePassword,
		arg.UserID,
		arg.FormatVersion,
		arg.KdfSalt,
		arg.KdfParameters,
		arg.EncryptedMasterKey,
	)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
	)
	return i, err
}
