// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encryption_v2.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEncryptionDeployment = `-- name: GetEncryptionDeployment :one
SELECT public_id FROM encryption_deployment WHERE singleton = true
`

func (q *Queries) GetEncryptionDeployment(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEncryptionDeployment)
	var public_id pgtype.UUID
	err := row.Scan(&public_id)
	return public_id, err
}
