// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encryption_v2.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserEncryptionIdentity = `-- name: CreateUserEncryptionIdentity :exec
INSERT INTO user_encryption_identities (
    user_id, generation, signing_public_key, recipient_public_key, recipient_key_id,
    certificate, certificate_signature, continuity_certificate, continuity_signature
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserEncryptionIdentityParams struct {
	UserID                int64
	Generation            int64
	SigningPublicKey      []byte
	RecipientPublicKey    []byte
	RecipientKeyID        []byte
	Certificate           []byte
	CertificateSignature  []byte
	ContinuityCertificate []byte
	ContinuitySignature   []byte
}

func (q *Queries) CreateUserEncryptionIdentity(ctx context.Context, arg CreateUserEncryptionIdentityParams) error {
	_, err := q.db.Exec(ctx, createUserEncryptionIdentity,
		arg.UserID,
		arg.Generation,
		arg.SigningPublicKey,
		arg.RecipientPublicKey,
		arg.RecipientKeyID,
		arg.Certificate,
		arg.CertificateSignature,
		arg.ContinuityCertificate,
		arg.ContinuitySignature,
	)
	return err
}

const createV2KeyBundle = `-- name: CreateV2KeyBundle :one
INSERT INTO user_key_bundles (
    user_id, format_version, kdf_salt, encrypted_master_key, recovery_encrypted_master_key,
    private_key_envelope, identity_generation, bundle_revision
) VALUES ($1, 2, $2, $3, $4, $5, $6, $7)
RETURNING user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision, identity_generation
`

type CreateV2KeyBundleParams struct {
	UserID                     int64
	KdfSalt                    []byte
	EncryptedMasterKey         []byte
	RecoveryEncryptedMasterKey []byte
	PrivateKeyEnvelope         []byte
	IdentityGeneration         pgtype.Int8
	BundleRevision             int64
}

func (q *Queries) CreateV2KeyBundle(ctx context.Context, arg CreateV2KeyBundleParams) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, createV2KeyBundle,
		arg.UserID,
		arg.KdfSalt,
		arg.EncryptedMasterKey,
		arg.RecoveryEncryptedMasterKey,
		arg.PrivateKeyEnvelope,
		arg.IdentityGeneration,
		arg.BundleRevision,
	)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
		&i.IdentityGeneration,
	)
	return i, err
}

const getEncryptionDeployment = `-- name: GetEncryptionDeployment :one
SELECT public_id FROM encryption_deployment WHERE singleton = true
`

func (q *Queries) GetEncryptionDeployment(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEncryptionDeployment)
	var public_id pgtype.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const getUserEncryptionIdentity = `-- name: GetUserEncryptionIdentity :one
SELECT user_id, generation, signing_public_key, recipient_public_key, recipient_key_id, certificate, continuity_certificate, created_at, certificate_signature, continuity_signature FROM user_encryption_identities WHERE user_id = $1 AND generation = $2
`

type GetUserEncryptionIdentityParams struct {
	UserID     int64
	Generation int64
}

func (q *Queries) GetUserEncryptionIdentity(ctx context.Context, arg GetUserEncryptionIdentityParams) (UserEncryptionIdentity, error) {
	row := q.db.QueryRow(ctx, getUserEncryptionIdentity, arg.UserID, arg.Generation)
	var i UserEncryptionIdentity
	err := row.Scan(
		&i.UserID,
		&i.Generation,
		&i.SigningPublicKey,
		&i.RecipientPublicKey,
		&i.RecipientKeyID,
		&i.Certificate,
		&i.ContinuityCertificate,
		&i.CreatedAt,
		&i.CertificateSignature,
		&i.ContinuitySignature,
	)
	return i, err
}

const getUserKeyBundleForUpdate = `-- name: GetUserKeyBundleForUpdate :one
SELECT user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision, identity_generation FROM user_key_bundles WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetUserKeyBundleForUpdate(ctx context.Context, userID int64) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, getUserKeyBundleForUpdate, userID)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
		&i.IdentityGeneration,
	)
	return i, err
}

const listUserEncryptionIdentities = `-- name: ListUserEncryptionIdentities :many
SELECT user_id, generation, signing_public_key, recipient_public_key, recipient_key_id, certificate, continuity_certificate, created_at, certificate_signature, continuity_signature FROM user_encryption_identities WHERE user_id = $1 ORDER BY generation
`

func (q *Queries) ListUserEncryptionIdentities(ctx context.Context, userID int64) ([]UserEncryptionIdentity, error) {
	rows, err := q.db.Query(ctx, listUserEncryptionIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEncryptionIdentity
	for rows.Next() {
		var i UserEncryptionIdentity
		if err := rows.Scan(
			&i.UserID,
			&i.Generation,
			&i.SigningPublicKey,
			&i.RecipientPublicKey,
			&i.RecipientKeyID,
			&i.Certificate,
			&i.ContinuityCertificate,
			&i.CreatedAt,
			&i.CertificateSignature,
			&i.ContinuitySignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateV2KeyBundle = `-- name: UpdateV2KeyBundle :one
UPDATE user_key_bundles
SET kdf_salt = $1, encrypted_master_key = $2,
    recovery_encrypted_master_key = $3,
    private_key_envelope = $4, identity_generation = $5,
    bundle_revision = $6, updated_at = now()
WHERE user_id = $7 AND format_version = 2
    AND identity_generation = $8 AND bundle_revision = $9
RETURNING user_id, format_version, kdf_salt, kdf_parameters, encrypted_master_key, recovery_encrypted_master_key, master_encrypted_recovery_key, created_at, updated_at, private_key_envelope, bundle_revision, identity_generation
`

type UpdateV2KeyBundleParams struct {
	KdfSalt                    []byte
	EncryptedMasterKey         []byte
	RecoveryEncryptedMasterKey []byte
	PrivateKeyEnvelope         []byte
	IdentityGeneration         pgtype.Int8
	BundleRevision             int64
	UserID                     int64
	ExpectedGeneration         pgtype.Int8
	ExpectedRevision           int64
}

func (q *Queries) UpdateV2KeyBundle(ctx context.Context, arg UpdateV2KeyBundleParams) (UserKeyBundle, error) {
	row := q.db.QueryRow(ctx, updateV2KeyBundle,
		arg.KdfSalt,
		arg.EncryptedMasterKey,
		arg.RecoveryEncryptedMasterKey,
		arg.PrivateKeyEnvelope,
		arg.IdentityGeneration,
		arg.BundleRevision,
		arg.UserID,
		arg.ExpectedGeneration,
		arg.ExpectedRevision,
	)
	var i UserKeyBundle
	err := row.Scan(
		&i.UserID,
		&i.FormatVersion,
		&i.KdfSalt,
		&i.KdfParameters,
		&i.EncryptedMasterKey,
		&i.RecoveryEncryptedMasterKey,
		&i.MasterEncryptedRecoveryKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrivateKeyEnvelope,
		&i.BundleRevision,
		&i.IdentityGeneration,
	)
	return i, err
}
