// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentFileByPublicIDAndOwner = `-- name: GetCurrentFileByPublicIDAndOwner :one
SELECT
    n.public_id AS node_public_id,
    n.name,
    n.encrypted_name,
    n.revision,
    l.public_id AS library_public_id,
    l.encryption_mode,
    v.public_id AS version_public_id,
    v.size_bytes,
    b.size_bytes AS stored_size_bytes,
    b.ciphertext_sha256,
    b.encryption_format,
    b.encrypted_file_key,
    sb.public_id AS backend_public_id,
    bl.object_key
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN file_versions v ON v.id = n.current_version_id
JOIN blobs b ON b.id = v.blob_id
JOIN blob_locations bl ON bl.blob_id = b.id AND bl.backend_id = l.backend_id AND bl.state = 'available'
JOIN storage_backends sb ON sb.id = bl.backend_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NULL
  AND l.owner_id = $2
`

type GetCurrentFileByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

type GetCurrentFileByPublicIDAndOwnerRow struct {
	NodePublicID     string
	Name             pgtype.Text
	EncryptedName    []byte
	Revision         int64
	LibraryPublicID  string
	EncryptionMode   string
	VersionPublicID  string
	SizeBytes        int64
	StoredSizeBytes  int64
	CiphertextSha256 []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
	BackendPublicID  string
	ObjectKey        string
}

func (q *Queries) GetCurrentFileByPublicIDAndOwner(ctx context.Context, arg GetCurrentFileByPublicIDAndOwnerParams) (GetCurrentFileByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCurrentFileByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var i GetCurrentFileByPublicIDAndOwnerRow
	err := row.Scan(
		&i.NodePublicID,
		&i.Name,
		&i.EncryptedName,
		&i.Revision,
		&i.LibraryPublicID,
		&i.EncryptionMode,
		&i.VersionPublicID,
		&i.SizeBytes,
		&i.StoredSizeBytes,
		&i.CiphertextSha256,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.BackendPublicID,
		&i.ObjectKey,
	)
	return i, err
}
