// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files_v2.sql

package db

import (
	"context"
)

const getV2CurrentFileByPublicIDAndOwner = `-- name: GetV2CurrentFileByPublicIDAndOwner :one
SELECT
    n.public_id AS node_public_id,
    n.revision,
    n.current_version_pointer,
    n.current_version_signature,
    l.public_id AS library_public_id,
    v.public_id AS version_public_id,
    v.size_bytes,
    b.size_bytes AS stored_size_bytes,
    b.ciphertext_sha256,
    k.encrypted_content_key,
    k.signed_manifest,
    k.manifest_signature,
    sb.public_id AS backend_public_id,
    bl.object_key
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN file_versions v ON v.id = n.current_version_id
JOIN file_version_keys k ON k.version_id = v.id
JOIN blobs b ON b.id = v.blob_id
JOIN blob_locations bl ON bl.blob_id = b.id AND bl.backend_id = l.backend_id AND bl.state = 'available'
JOIN storage_backends sb ON sb.id = bl.backend_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NULL
  AND l.owner_id = $2 AND l.encryption_format = 'v2'
`

type GetV2CurrentFileByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

type GetV2CurrentFileByPublicIDAndOwnerRow struct {
	NodePublicID            string
	Revision                int64
	CurrentVersionPointer   []byte
	CurrentVersionSignature []byte
	LibraryPublicID         string
	VersionPublicID         string
	SizeBytes               int64
	StoredSizeBytes         int64
	CiphertextSha256        []byte
	EncryptedContentKey     []byte
	SignedManifest          []byte
	ManifestSignature       []byte
	BackendPublicID         string
	ObjectKey               string
}

func (q *Queries) GetV2CurrentFileByPublicIDAndOwner(ctx context.Context, arg GetV2CurrentFileByPublicIDAndOwnerParams) (GetV2CurrentFileByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getV2CurrentFileByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var i GetV2CurrentFileByPublicIDAndOwnerRow
	err := row.Scan(
		&i.NodePublicID,
		&i.Revision,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.LibraryPublicID,
		&i.VersionPublicID,
		&i.SizeBytes,
		&i.StoredSizeBytes,
		&i.CiphertextSha256,
		&i.EncryptedContentKey,
		&i.SignedManifest,
		&i.ManifestSignature,
		&i.BackendPublicID,
		&i.ObjectKey,
	)
	return i, err
}
