// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFileCurrentVersion = `-- name: ClearFileCurrentVersion :exec
UPDATE nodes SET current_version_id = NULL WHERE id = $1 AND kind = 'file'
`

func (q *Queries) ClearFileCurrentVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearFileCurrentVersion, id)
	return err
}

const deleteFileNode = `-- name: DeleteFileNode :execrows
DELETE FROM nodes WHERE id = $1 AND kind = 'file'
`

func (q *Queries) DeleteFileNode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFileVersions = `-- name: DeleteFileVersions :many
DELETE FROM file_versions WHERE node_id = $1
RETURNING blob_id
`

func (q *Queries) DeleteFileVersions(ctx context.Context, nodeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteFileVersions, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var blob_id int64
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUnreferencedBlobLocations = `-- name: DeleteUnreferencedBlobLocations :many
WITH deleted AS (
    DELETE FROM blob_locations bl
    WHERE bl.blob_id = ANY($1::bigint[])
      AND NOT EXISTS (SELECT 1 FROM file_versions v WHERE v.blob_id = bl.blob_id)
    RETURNING bl.backend_id, bl.object_key
)
SELECT sb.public_id AS backend_public_id, deleted.object_key
FROM deleted
JOIN storage_backends sb ON sb.id = deleted.backend_id
`

type DeleteUnreferencedBlobLocationsRow struct {
	BackendPublicID string
	ObjectKey       string
}

func (q *Queries) DeleteUnreferencedBlobLocations(ctx context.Context, blobIds []int64) ([]DeleteUnreferencedBlobLocationsRow, error) {
	rows, err := q.db.Query(ctx, deleteUnreferencedBlobLocations, blobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteUnreferencedBlobLocationsRow
	for rows.Next() {
		var i DeleteUnreferencedBlobLocationsRow
		if err := rows.Scan(&i.BackendPublicID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUnreferencedBlobs = `-- name: DeleteUnreferencedBlobs :exec
DELETE FROM blobs b
WHERE b.id = ANY($1::bigint[])
  AND NOT EXISTS (SELECT 1 FROM file_versions v WHERE v.blob_id = b.id)
`

func (q *Queries) DeleteUnreferencedBlobs(ctx context.Context, blobIds []int64) error {
	_, err := q.db.Exec(ctx, deleteUnreferencedBlobs, blobIds)
	return err
}

const detachUploadSessionsFromNode = `-- name: DetachUploadSessionsFromNode :exec
UPDATE upload_sessions
SET target_node_id = CASE WHEN target_node_id = $1 THEN NULL ELSE target_node_id END,
    published_node_id = CASE WHEN published_node_id = $1 THEN NULL ELSE published_node_id END,
    published_version_id = CASE WHEN published_node_id = $1 THEN NULL ELSE published_version_id END,
    updated_at = now()
WHERE target_node_id = $1 OR published_node_id = $1
`

func (q *Queries) DetachUploadSessionsFromNode(ctx context.Context, nodeID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, detachUploadSessionsFromNode, nodeID)
	return err
}

const getCurrentFileByPublicIDAndOwner = `-- name: GetCurrentFileByPublicIDAndOwner :one
SELECT
    n.public_id AS node_public_id,
    n.name,
    n.encrypted_name,
    n.revision,
    l.public_id AS library_public_id,
    l.encryption_mode,
    v.public_id AS version_public_id,
    v.size_bytes,
    b.size_bytes AS stored_size_bytes,
    b.ciphertext_sha256,
    b.encryption_format,
    b.encrypted_file_key,
    sb.public_id AS backend_public_id,
    bl.object_key
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN file_versions v ON v.id = n.current_version_id
JOIN blobs b ON b.id = v.blob_id
JOIN blob_locations bl ON bl.blob_id = b.id AND bl.backend_id = l.backend_id AND bl.state = 'available'
JOIN storage_backends sb ON sb.id = bl.backend_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NULL
  AND l.owner_id = $2
`

type GetCurrentFileByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

type GetCurrentFileByPublicIDAndOwnerRow struct {
	NodePublicID     string
	Name             pgtype.Text
	EncryptedName    []byte
	Revision         int64
	LibraryPublicID  string
	EncryptionMode   string
	VersionPublicID  string
	SizeBytes        int64
	StoredSizeBytes  int64
	CiphertextSha256 []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
	BackendPublicID  string
	ObjectKey        string
}

func (q *Queries) GetCurrentFileByPublicIDAndOwner(ctx context.Context, arg GetCurrentFileByPublicIDAndOwnerParams) (GetCurrentFileByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getCurrentFileByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var i GetCurrentFileByPublicIDAndOwnerRow
	err := row.Scan(
		&i.NodePublicID,
		&i.Name,
		&i.EncryptedName,
		&i.Revision,
		&i.LibraryPublicID,
		&i.EncryptionMode,
		&i.VersionPublicID,
		&i.SizeBytes,
		&i.StoredSizeBytes,
		&i.CiphertextSha256,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.BackendPublicID,
		&i.ObjectKey,
	)
	return i, err
}

const getExpiredTrashedFileForUpdate = `-- name: GetExpiredTrashedFileForUpdate :one
SELECT id, library_id
FROM nodes
WHERE id = $1 AND kind = 'file' AND trashed_at <= now() - INTERVAL '30 days'
FOR UPDATE
`

type GetExpiredTrashedFileForUpdateRow struct {
	ID        int64
	LibraryID int64
}

func (q *Queries) GetExpiredTrashedFileForUpdate(ctx context.Context, id int64) (GetExpiredTrashedFileForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getExpiredTrashedFileForUpdate, id)
	var i GetExpiredTrashedFileForUpdateRow
	err := row.Scan(&i.ID, &i.LibraryID)
	return i, err
}

const getFileNodeByPublicIDAndOwner = `-- name: GetFileNodeByPublicIDAndOwner :one
SELECT n.id, n.library_id, l.public_id AS library_public_id, l.encryption_mode,
       parent.public_id AS parent_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN nodes parent ON parent.id = n.parent_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NULL
  AND l.owner_id = $2
`

type GetFileNodeByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

type GetFileNodeByPublicIDAndOwnerRow struct {
	ID              int64
	LibraryID       int64
	LibraryPublicID string
	EncryptionMode  string
	ParentPublicID  string
}

func (q *Queries) GetFileNodeByPublicIDAndOwner(ctx context.Context, arg GetFileNodeByPublicIDAndOwnerParams) (GetFileNodeByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getFileNodeByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var i GetFileNodeByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.LibraryPublicID,
		&i.EncryptionMode,
		&i.ParentPublicID,
	)
	return i, err
}

const getMoveDestination = `-- name: GetMoveDestination :one
SELECT l.id, l.public_id, l.name, l.backend_id, l.encryption_mode,
       root.id AS root_node_id, root.public_id AS root_node_public_id
FROM libraries l
JOIN nodes root ON root.id = l.root_node_id
WHERE l.public_id = $1 AND l.owner_id = $2
`

type GetMoveDestinationParams struct {
	LibraryPublicID string
	OwnerID         int64
}

type GetMoveDestinationRow struct {
	ID               int64
	PublicID         string
	Name             pgtype.Text
	BackendID        int64
	EncryptionMode   string
	RootNodeID       int64
	RootNodePublicID string
}

func (q *Queries) GetMoveDestination(ctx context.Context, arg GetMoveDestinationParams) (GetMoveDestinationRow, error) {
	row := q.db.QueryRow(ctx, getMoveDestination, arg.LibraryPublicID, arg.OwnerID)
	var i GetMoveDestinationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.BackendID,
		&i.EncryptionMode,
		&i.RootNodeID,
		&i.RootNodePublicID,
	)
	return i, err
}

const getMoveFolder = `-- name: GetMoveFolder :one
SELECT n.id, n.public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.public_id = $1 AND l.owner_id = $2
  AND n.library_id = $3 AND n.kind = 'folder' AND n.trashed_at IS NULL
`

type GetMoveFolderParams struct {
	NodePublicID string
	OwnerID      int64
	LibraryID    int64
}

type GetMoveFolderRow struct {
	ID       int64
	PublicID string
}

func (q *Queries) GetMoveFolder(ctx context.Context, arg GetMoveFolderParams) (GetMoveFolderRow, error) {
	row := q.db.QueryRow(ctx, getMoveFolder, arg.NodePublicID, arg.OwnerID, arg.LibraryID)
	var i GetMoveFolderRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const getTrashedFileCursorByPublicIDAndOwner = `-- name: GetTrashedFileCursorByPublicIDAndOwner :one
SELECT n.id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NOT NULL
  AND l.owner_id = $2
`

type GetTrashedFileCursorByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

func (q *Queries) GetTrashedFileCursorByPublicIDAndOwner(ctx context.Context, arg GetTrashedFileCursorByPublicIDAndOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTrashedFileCursorByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTrashedFileForUpdate = `-- name: GetTrashedFileForUpdate :one
SELECT id, library_id
FROM nodes
WHERE id = $1 AND kind = 'file' AND trashed_at IS NOT NULL
FOR UPDATE
`

type GetTrashedFileForUpdateRow struct {
	ID        int64
	LibraryID int64
}

func (q *Queries) GetTrashedFileForUpdate(ctx context.Context, id int64) (GetTrashedFileForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTrashedFileForUpdate, id)
	var i GetTrashedFileForUpdateRow
	err := row.Scan(&i.ID, &i.LibraryID)
	return i, err
}

const getTrashedFileNodeByPublicIDAndOwner = `-- name: GetTrashedFileNodeByPublicIDAndOwner :one
SELECT n.id, n.library_id, n.trashed_at, l.public_id AS library_public_id,
       parent.public_id AS parent_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN nodes parent ON parent.id = n.parent_id
WHERE n.public_id = $1 AND n.kind = 'file' AND n.trashed_at IS NOT NULL
  AND l.owner_id = $2
`

type GetTrashedFileNodeByPublicIDAndOwnerParams struct {
	NodePublicID string
	OwnerID      int64
}

type GetTrashedFileNodeByPublicIDAndOwnerRow struct {
	ID              int64
	LibraryID       int64
	TrashedAt       pgtype.Timestamptz
	LibraryPublicID string
	ParentPublicID  string
}

func (q *Queries) GetTrashedFileNodeByPublicIDAndOwner(ctx context.Context, arg GetTrashedFileNodeByPublicIDAndOwnerParams) (GetTrashedFileNodeByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getTrashedFileNodeByPublicIDAndOwner, arg.NodePublicID, arg.OwnerID)
	var i GetTrashedFileNodeByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.TrashedAt,
		&i.LibraryPublicID,
		&i.ParentPublicID,
	)
	return i, err
}

const listExpiredTrashedFileIDs = `-- name: ListExpiredTrashedFileIDs :many
SELECT id
FROM nodes
WHERE kind = 'file' AND trashed_at <= now() - INTERVAL '30 days'
ORDER BY trashed_at, id
LIMIT $1
`

func (q *Queries) ListExpiredTrashedFileIDs(ctx context.Context, limit int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, listExpiredTrashedFileIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedFilesByOwner = `-- name: ListTrashedFilesByOwner :many
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at, n.key_epoch, n.metadata_revision, n.encrypted_metadata, n.metadata_signature, n.current_version_pointer, n.current_version_signature, n.visible_encryption_generation, l.public_id AS library_public_id, l.name AS library_name,
       l.encryption_mode, parent.public_id AS parent_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN nodes parent ON parent.id = n.parent_id
WHERE l.owner_id = $1 AND n.kind = 'file' AND n.trashed_at IS NOT NULL
  AND n.id > $2
ORDER BY n.id
LIMIT $3
`

type ListTrashedFilesByOwnerParams struct {
	OwnerID   int64
	AfterID   int64
	PageLimit int32
}

type ListTrashedFilesByOwnerRow struct {
	ID                          int64
	PublicID                    string
	LibraryID                   int64
	ParentID                    pgtype.Int8
	Kind                        string
	Name                        pgtype.Text
	EncryptedName               []byte
	NameToken                   []byte
	CurrentVersionID            pgtype.Int8
	Revision                    int64
	TrashedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	KeyEpoch                    int64
	MetadataRevision            int64
	EncryptedMetadata           []byte
	MetadataSignature           []byte
	CurrentVersionPointer       []byte
	CurrentVersionSignature     []byte
	VisibleEncryptionGeneration int64
	LibraryPublicID             string
	LibraryName                 pgtype.Text
	EncryptionMode              string
	ParentPublicID              string
}

func (q *Queries) ListTrashedFilesByOwner(ctx context.Context, arg ListTrashedFilesByOwnerParams) ([]ListTrashedFilesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTrashedFilesByOwner, arg.OwnerID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashedFilesByOwnerRow
	for rows.Next() {
		var i ListTrashedFilesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.CurrentVersionID,
			&i.Revision,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyEpoch,
			&i.MetadataRevision,
			&i.EncryptedMetadata,
			&i.MetadataSignature,
			&i.CurrentVersionPointer,
			&i.CurrentVersionSignature,
			&i.VisibleEncryptionGeneration,
			&i.LibraryPublicID,
			&i.LibraryName,
			&i.EncryptionMode,
			&i.ParentPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFileNode = `-- name: MoveFileNode :one
WITH file_blobs AS (
    SELECT DISTINCT v.blob_id
    FROM file_versions v
    WHERE v.node_id = $3
), movable AS (
    SELECT (SELECT library_id FROM nodes WHERE id = $3) = $1
      OR NOT EXISTS (
        SELECT 1
        FROM file_versions v
        JOIN file_blobs b ON b.blob_id = v.blob_id
        WHERE v.node_id <> $3
    ) AS ok
), removed_tags AS (
    DELETE FROM file_tags
    WHERE node_id = $3
      AND library_id <> $1
), moved_uploads AS (
    UPDATE upload_sessions
    SET library_id = $1,
        parent_id = $2, updated_at = now()
    WHERE (target_node_id = $3 OR published_node_id = $3)
      AND (SELECT ok FROM movable)
), moved_locations AS (
    UPDATE blob_locations
    SET library_id = $1, updated_at = now()
    WHERE blob_id IN (SELECT blob_id FROM file_blobs) AND (SELECT ok FROM movable)
), moved_versions AS (
    UPDATE file_versions
    SET library_id = $1
    WHERE node_id = $3 AND (SELECT ok FROM movable)
), moved_blobs AS (
    UPDATE blobs
    SET library_id = $1
    WHERE id IN (SELECT blob_id FROM file_blobs) AND (SELECT ok FROM movable)
)
UPDATE nodes
SET library_id = $1, parent_id = $2, updated_at = now()
WHERE nodes.id = $3 AND nodes.kind = 'file' AND nodes.trashed_at IS NULL AND (SELECT ok FROM movable)
RETURNING nodes.id, nodes.public_id, nodes.library_id, nodes.parent_id, nodes.kind, nodes.name, nodes.encrypted_name, nodes.name_token, nodes.current_version_id, nodes.revision, nodes.trashed_at, nodes.created_at, nodes.updated_at, nodes.key_epoch, nodes.metadata_revision, nodes.encrypted_metadata, nodes.metadata_signature, nodes.current_version_pointer, nodes.current_version_signature, nodes.visible_encryption_generation
`

type MoveFileNodeParams struct {
	DestinationLibraryID int64
	DestinationParentID  pgtype.Int8
	NodeID               int64
}

func (q *Queries) MoveFileNode(ctx context.Context, arg MoveFileNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, moveFileNode, arg.DestinationLibraryID, arg.DestinationParentID, arg.NodeID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const renameFileNode = `-- name: RenameFileNode :one
UPDATE nodes
SET name = $2, encrypted_name = $3, name_token = $4, updated_at = now()
WHERE id = $1 AND kind = 'file' AND trashed_at IS NULL
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation
`

type RenameFileNodeParams struct {
	ID            int64
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
}

func (q *Queries) RenameFileNode(ctx context.Context, arg RenameFileNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, renameFileNode,
		arg.ID,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const restoreFileNode = `-- name: RestoreFileNode :one
UPDATE nodes
SET trashed_at = NULL, updated_at = now()
WHERE id = $1 AND kind = 'file' AND trashed_at IS NOT NULL
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation
`

func (q *Queries) RestoreFileNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, restoreFileNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const setFileTrashedAt = `-- name: SetFileTrashedAt :exec
UPDATE nodes SET trashed_at = $2, updated_at = now() WHERE id = $1 AND kind = 'file'
`

type SetFileTrashedAtParams struct {
	ID        int64
	TrashedAt pgtype.Timestamptz
}

func (q *Queries) SetFileTrashedAt(ctx context.Context, arg SetFileTrashedAtParams) error {
	_, err := q.db.Exec(ctx, setFileTrashedAt, arg.ID, arg.TrashedAt)
	return err
}

const trashFileNode = `-- name: TrashFileNode :one
UPDATE nodes
SET trashed_at = now(), updated_at = now()
WHERE id = $1 AND kind = 'file' AND trashed_at IS NULL
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation
`

func (q *Queries) TrashFileNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, trashFileNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}
