// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInviteCode = `-- name: CreateInviteCode :one
INSERT INTO invite_codes (public_id, code, created_by)
VALUES ($1, $2, $3)
RETURNING id, public_id, code, created_by, used_by, created_at, used_at
`

type CreateInviteCodeParams struct {
	PublicID  string
	Code      string
	CreatedBy int64
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (InviteCode, error) {
	row := q.db.QueryRow(ctx, createInviteCode, arg.PublicID, arg.Code, arg.CreatedBy)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteInviteCode = `-- name: DeleteInviteCode :execrows
DELETE FROM invite_codes
WHERE public_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteInviteCode(ctx context.Context, publicID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInviteCode, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInviteCodes = `-- name: ListInviteCodes :many
SELECT id, public_id, code, created_by, used_by, created_at, used_at FROM invite_codes ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInviteCodes(ctx context.Context) ([]InviteCode, error) {
	rows, err := q.db.Query(ctx, listInviteCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InviteCode
	for rows.Next() {
		var i InviteCode
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Code,
			&i.CreatedBy,
			&i.UsedBy,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnusedInviteCode = `-- name: LockUnusedInviteCode :one
SELECT id, public_id, code, created_by, used_by, created_at, used_at FROM invite_codes
WHERE lower(code) = lower($1::text) AND used_at IS NULL
FOR UPDATE
`

func (q *Queries) LockUnusedInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, lockUnusedInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const markInviteCodeUsed = `-- name: MarkInviteCodeUsed :exec
UPDATE invite_codes
SET used_by = $1, used_at = now()
WHERE id = $2
`

type MarkInviteCodeUsedParams struct {
	UsedBy pgtype.Int8
	ID     int64
}

func (q *Queries) MarkInviteCodeUsed(ctx context.Context, arg MarkInviteCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteCodeUsed, arg.UsedBy, arg.ID)
	return err
}
