// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, public_id, owner_id, backend_id, root_node_id, name, encryption_mode, key_envelope)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_id, owner_id, backend_id, root_node_id, name, encryption_mode, key_envelope, created_at, updated_at
`

type CreateLibraryParams struct {
	ID             int64
	PublicID       string
	OwnerID        int64
	BackendID      int64
	RootNodeID     int64
	Name           string
	EncryptionMode string
	KeyEnvelope    []byte
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary,
		arg.ID,
		arg.PublicID,
		arg.OwnerID,
		arg.BackendID,
		arg.RootNodeID,
		arg.Name,
		arg.EncryptionMode,
		arg.KeyEnvelope,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.BackendID,
		&i.RootNodeID,
		&i.Name,
		&i.EncryptionMode,
		&i.KeyEnvelope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (public_id, library_id, parent_id, kind, name, encrypted_name, name_token)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at
`

type CreateNodeParams struct {
	PublicID      string
	LibraryID     int64
	ParentID      pgtype.Int8
	Kind          string
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNodeWithID = `-- name: CreateNodeWithID :one
INSERT INTO nodes (id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at
`

type CreateNodeWithIDParams struct {
	ID            int64
	PublicID      string
	LibraryID     int64
	ParentID      pgtype.Int8
	Kind          string
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
}

func (q *Queries) CreateNodeWithID(ctx context.Context, arg CreateNodeWithIDParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNodeWithID,
		arg.ID,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledBackendByPublicID = `-- name: GetEnabledBackendByPublicID :one
SELECT id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at FROM storage_backends WHERE public_id = $1 AND enabled = true
`

func (q *Queries) GetEnabledBackendByPublicID(ctx context.Context, publicID string) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, getEnabledBackendByPublicID, publicID)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EncryptedSecrets,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryByPublicIDAndOwner = `-- name: GetLibraryByPublicIDAndOwner :one
SELECT l.id, l.public_id, l.owner_id, l.backend_id, l.root_node_id, l.name, l.encryption_mode, l.key_envelope, l.created_at, l.updated_at, b.public_id AS backend_public_id, b.name AS backend_name, b.type AS backend_type,
       root.public_id AS root_node_public_id
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
JOIN nodes root ON root.id = l.root_node_id
WHERE l.public_id = $1 AND l.owner_id = $2
`

type GetLibraryByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

type GetLibraryByPublicIDAndOwnerRow struct {
	ID               int64
	PublicID         string
	OwnerID          int64
	BackendID        int64
	RootNodeID       int64
	Name             string
	EncryptionMode   string
	KeyEnvelope      []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	BackendPublicID  string
	BackendName      string
	BackendType      string
	RootNodePublicID string
}

func (q *Queries) GetLibraryByPublicIDAndOwner(ctx context.Context, arg GetLibraryByPublicIDAndOwnerParams) (GetLibraryByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getLibraryByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i GetLibraryByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.BackendID,
		&i.RootNodeID,
		&i.Name,
		&i.EncryptionMode,
		&i.KeyEnvelope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackendPublicID,
		&i.BackendName,
		&i.BackendType,
		&i.RootNodePublicID,
	)
	return i, err
}

const getNodeByPublicIDAndOwner = `-- name: GetNodeByPublicIDAndOwner :one
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.public_id = $1 AND l.owner_id = $2
`

type GetNodeByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) GetNodeByPublicIDAndOwner(ctx context.Context, arg GetNodeByPublicIDAndOwnerParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildNodes = `-- name: ListChildNodes :many
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at FROM nodes n
WHERE n.library_id = $1 AND n.parent_id = $2
  AND n.trashed_at IS NULL AND n.id > $3
  AND ($4::bigint = 0 OR EXISTS (
      SELECT 1 FROM file_tags ft WHERE ft.node_id = n.id AND ft.tag_id = $4
  ))
ORDER BY n.id
LIMIT $5
`

type ListChildNodesParams struct {
	LibraryID int64
	ParentID  pgtype.Int8
	AfterID   int64
	TagID     int64
	PageLimit int32
}

func (q *Queries) ListChildNodes(ctx context.Context, arg ListChildNodesParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listChildNodes,
		arg.LibraryID,
		arg.ParentID,
		arg.AfterID,
		arg.TagID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.CurrentVersionID,
			&i.Revision,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledStorageBackends = `-- name: ListEnabledStorageBackends :many
SELECT public_id, name, type FROM storage_backends WHERE enabled = true ORDER BY lower(name), id
`

type ListEnabledStorageBackendsRow struct {
	PublicID string
	Name     string
	Type     string
}

func (q *Queries) ListEnabledStorageBackends(ctx context.Context) ([]ListEnabledStorageBackendsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledStorageBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledStorageBackendsRow
	for rows.Next() {
		var i ListEnabledStorageBackendsRow
		if err := rows.Scan(&i.PublicID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesByOwner = `-- name: ListLibrariesByOwner :many
SELECT l.id, l.public_id, l.owner_id, l.backend_id, l.root_node_id, l.name, l.encryption_mode, l.key_envelope, l.created_at, l.updated_at, b.public_id AS backend_public_id, b.name AS backend_name, b.type AS backend_type,
       root.public_id AS root_node_public_id
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
JOIN nodes root ON root.id = l.root_node_id
WHERE l.owner_id = $1
ORDER BY l.name, l.id
`

type ListLibrariesByOwnerRow struct {
	ID               int64
	PublicID         string
	OwnerID          int64
	BackendID        int64
	RootNodeID       int64
	Name             string
	EncryptionMode   string
	KeyEnvelope      []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	BackendPublicID  string
	BackendName      string
	BackendType      string
	RootNodePublicID string
}

func (q *Queries) ListLibrariesByOwner(ctx context.Context, ownerID int64) ([]ListLibrariesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLibrariesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibrariesByOwnerRow
	for rows.Next() {
		var i ListLibrariesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.BackendID,
			&i.RootNodeID,
			&i.Name,
			&i.EncryptionMode,
			&i.KeyEnvelope,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BackendPublicID,
			&i.BackendName,
			&i.BackendType,
			&i.RootNodePublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextLibraryID = `-- name: NextLibraryID :one
SELECT nextval('libraries_id_seq')::bigint
`

func (q *Queries) NextLibraryID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextLibraryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextNodeID = `-- name: NextNodeID :one
SELECT nextval('nodes_id_seq')::bigint
`

func (q *Queries) NextNodeID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextNodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
