// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID        int64
	PublicID  string
	Action    string
	ActorType string
	ActorID   pgtype.Int8
	SubjectID pgtype.Int8
	TargetID  string
	Details   []byte
	IpAddress *netip.Addr
	UserAgent string
	RequestID string
	CreatedAt pgtype.Timestamptz
}

type Blob struct {
	ID               int64
	PublicID         string
	LibraryID        int64
	SizeBytes        int64
	CiphertextSha256 []byte
	DedupFingerprint []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
	CreatedAt        pgtype.Timestamptz
}

type BlobLocation struct {
	ID         int64
	PublicID   string
	BlobID     int64
	LibraryID  int64
	BackendID  int64
	ObjectKey  string
	State      string
	VerifiedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EncryptionDeployment struct {
	Singleton bool
	PublicID  pgtype.UUID
}

type EncryptionRotation struct {
	ID                   int64
	PublicID             string
	OwnerID              int64
	LibraryID            int64
	RootNodeID           int64
	BarrierGeneration    int64
	ExpectedRevisions    []byte
	State                string
	EncryptedResumeState []byte
	CommittedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type EncryptionRotationBatch struct {
	RotationID  int64
	BatchNumber int64
	RecordCount int32
	Records     []byte
	RecordsHash []byte
	CreatedAt   pgtype.Timestamptz
}

type FileTag struct {
	NodeID    int64
	TagID     int64
	LibraryID int64
	CreatedAt pgtype.Timestamptz
}

type FileVersion struct {
	ID                    int64
	PublicID              string
	NodeID                int64
	LibraryID             int64
	Ordinal               int64
	BlobID                int64
	SizeBytes             int64
	ContentSha256         []byte
	RestoredFromVersionID pgtype.Int8
	CreatedAt             pgtype.Timestamptz
}

type FileVersionKey struct {
	VersionID           int64
	NodeID              int64
	NodeEpoch           int64
	Generation          int64
	ContentID           []byte
	EncryptedContentKey []byte
	SignedManifest      []byte
}

type InviteCode struct {
	ID        int64
	PublicID  string
	Code      string
	CreatedBy int64
	UsedBy    pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Library struct {
	ID                     int64
	PublicID               string
	OwnerID                int64
	BackendID              int64
	RootNodeID             int64
	Name                   pgtype.Text
	EncryptionMode         string
	KeyEnvelope            []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	EncryptionFormat       string
	EncryptedRootMetadata  []byte
	OwnerRootEnvelope      []byte
	AccessPolicyGeneration int64
}

type LibraryReplication struct {
	ID                   int64
	PublicID             string
	OwnerID              int64
	SourceLibraryID      int64
	DestinationLibraryID int64
	State                string
	LastError            pgtype.Text
	LastSyncedAt         pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Node struct {
	ID                          int64
	PublicID                    string
	LibraryID                   int64
	ParentID                    pgtype.Int8
	Kind                        string
	Name                        pgtype.Text
	EncryptedName               []byte
	NameToken                   []byte
	CurrentVersionID            pgtype.Int8
	Revision                    int64
	TrashedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	KeyEpoch                    int64
	MetadataRevision            int64
	EncryptedMetadata           []byte
	MetadataSignature           []byte
	CurrentVersionPointer       []byte
	CurrentVersionSignature     []byte
	VisibleEncryptionGeneration int64
}

type NodeKeyEnvelope struct {
	ChildNodeID    int64
	ParentNodeID   int64
	ChildEpoch     int64
	ParentEpoch    int64
	Generation     int64
	Ciphertext     []byte
	OwnerSignature []byte
	LibraryID      int64
}

type Passkey struct {
	ID                int64
	PublicID          string
	UserID            int64
	RpID              string
	CredentialID      []byte
	Name              string
	PublicKey         []byte
	AttestationType   string
	AttestationFormat string
	Attestation       []byte
	Extensions        []byte
	Transports        []string
	Aaguid            []byte
	Attachment        string
	SignCount         int64
	Flags             int16
	CreatedAt         pgtype.Timestamptz
	LastUsedAt        pgtype.Timestamptz
}

type PasskeyUser struct {
	UserID int64
	Handle []byte
}

type PublicLink struct {
	ID              int64
	PublicID        string
	OwnerID         int64
	LibraryID       int64
	RootNodeID      int64
	TokenHash       []byte
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	PolicyRevision  int64
	ImmutablePolicy []byte
	CreatedAt       pgtype.Timestamptz
}

type PublicLinkCapsule struct {
	LinkID              int64
	TargetEpoch         int64
	CapsuleRevision     int64
	Ciphertext          []byte
	Nonce               []byte
	PasswordProfile     pgtype.Text
	PasswordSalt        []byte
	AuthenticatedFields []byte
}

type PublicLinkManagement struct {
	LinkID        int64
	OwnerEnvelope []byte
}

type QuotaSetting struct {
	ID                bool
	DefaultLimitBytes pgtype.Int8
}

type ReplicationNode struct {
	ReplicationID     int64
	SourceNodeID      int64
	DestinationNodeID int64
}

type Session struct {
	TokenHash []byte
	PublicID  string
	UserID    int64
	UserAgent string
	IpAddress *netip.Addr
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Setting struct {
	Key   string
	Value string
}

type Share struct {
	ID          int64
	PublicID    string
	OwnerID     int64
	RecipientID int64
	LibraryID   int64
	RootNodeID  int64
	Role        string
	State       string
	ExpiresAt   pgtype.Timestamptz
	Certificate []byte
	Revision    int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShareKeyEnvelope struct {
	ShareID         int64
	GrantRevision   int64
	RecipientKeyID  []byte
	TargetEpoch     int64
	Ciphertext      []byte
	EncapsulatedKey []byte
	SignerRecord    []byte
}

type StorageBackend struct {
	ID               int64
	PublicID         string
	Name             string
	Type             string
	Config           []byte
	EncryptedSecrets string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Tag struct {
	ID             int64
	PublicID       string
	LibraryID      int64
	Name           pgtype.Text
	EncryptedName  []byte
	NameToken      []byte
	Color          pgtype.Text
	EncryptedColor []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UploadSession struct {
	ID                 int64
	PublicID           string
	OwnerID            int64
	LibraryID          int64
	ParentID           int64
	TargetNodeID       pgtype.Int8
	ExpectedRevision   pgtype.Int8
	Name               pgtype.Text
	EncryptedName      []byte
	NameToken          []byte
	DeclaredSize       int64
	UploadOffset       int64
	StagingKey         string
	DestinationKey     string
	State              string
	DedupFingerprint   []byte
	EncryptionFormat   pgtype.Text
	EncryptedFileKey   []byte
	PublishedNodeID    pgtype.Int8
	PublishedVersionID pgtype.Int8
	FailureCode        pgtype.Text
	FailureMessage     pgtype.Text
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

type User struct {
	ID           int64
	PublicID     string
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsAdmin      bool
}

type UserBackendQuota struct {
	UserID     int64
	BackendID  int64
	LimitBytes pgtype.Int8
}

type UserDefaultQuota struct {
	UserID     int64
	LimitBytes pgtype.Int8
}

type UserEncryptionContact struct {
	UserID               int64
	Revision             int64
	EncryptedStore       []byte
	Signature            []byte
	PreviousRevisionHash []byte
	UpdatedAt            pgtype.Timestamptz
}

type UserEncryptionIdentity struct {
	UserID                int64
	Generation            int64
	SigningPublicKey      []byte
	RecipientPublicKey    []byte
	RecipientKeyID        []byte
	Certificate           []byte
	ContinuityCertificate []byte
	CreatedAt             pgtype.Timestamptz
}

type UserKeyBundle struct {
	UserID                     int64
	FormatVersion              int32
	KdfSalt                    []byte
	KdfParameters              []byte
	EncryptedMasterKey         []byte
	RecoveryEncryptedMasterKey []byte
	MasterEncryptedRecoveryKey []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	PrivateKeyEnvelope         []byte
	BundleRevision             int64
}

type WebauthnCeremony struct {
	Challenge   string
	Kind        string
	UserID      pgtype.Int8
	SessionData []byte
	ExpiresAt   pgtype.Timestamptz
}
