// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeWebAuthnCeremony = `-- name: ConsumeWebAuthnCeremony :one
DELETE FROM webauthn_ceremonies
WHERE challenge = $1 AND kind = $2
    AND user_id IS NOT DISTINCT FROM $3::bigint
    AND expires_at > now()
RETURNING session_data
`

type ConsumeWebAuthnCeremonyParams struct {
	Challenge string
	Kind      string
	UserID    pgtype.Int8
}

func (q *Queries) ConsumeWebAuthnCeremony(ctx context.Context, arg ConsumeWebAuthnCeremonyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeWebAuthnCeremony, arg.Challenge, arg.Kind, arg.UserID)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (
    public_id, user_id, rp_id, credential_id, name, public_key, attestation_type, attestation_format,
    attestation, extensions, transports, aaguid, attachment, sign_count, flags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, public_id, user_id, rp_id, credential_id, name, public_key, attestation_type, attestation_format, attestation, extensions, transports, aaguid, attachment, sign_count, flags, created_at, last_used_at
`

type CreatePasskeyParams struct {
	PublicID          string
	UserID            int64
	RpID              string
	CredentialID      []byte
	Name              string
	PublicKey         []byte
	AttestationType   string
	AttestationFormat string
	Attestation       []byte
	Extensions        []byte
	Transports        []string
	Aaguid            []byte
	Attachment        string
	SignCount         int64
	Flags             int16
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.PublicID,
		arg.UserID,
		arg.RpID,
		arg.CredentialID,
		arg.Name,
		arg.PublicKey,
		arg.AttestationType,
		arg.AttestationFormat,
		arg.Attestation,
		arg.Extensions,
		arg.Transports,
		arg.Aaguid,
		arg.Attachment,
		arg.SignCount,
		arg.Flags,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RpID,
		&i.CredentialID,
		&i.Name,
		&i.PublicKey,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.Attestation,
		&i.Extensions,
		&i.Transports,
		&i.Aaguid,
		&i.Attachment,
		&i.SignCount,
		&i.Flags,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createWebAuthnCeremony = `-- name: CreateWebAuthnCeremony :exec
INSERT INTO webauthn_ceremonies (challenge, kind, user_id, session_data, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWebAuthnCeremonyParams struct {
	Challenge   string
	Kind        string
	UserID      pgtype.Int8
	SessionData []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateWebAuthnCeremony(ctx context.Context, arg CreateWebAuthnCeremonyParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnCeremony,
		arg.Challenge,
		arg.Kind,
		arg.UserID,
		arg.SessionData,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredWebAuthnCeremonies = `-- name: DeleteExpiredWebAuthnCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredWebAuthnCeremonies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredWebAuthnCeremonies)
	return err
}

const deletePasskey = `-- name: DeletePasskey :one
DELETE FROM passkeys WHERE public_id = $1 AND user_id = $2
RETURNING name
`

type DeletePasskeyParams struct {
	PublicID string
	UserID   int64
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (string, error) {
	row := q.db.QueryRow(ctx, deletePasskey, arg.PublicID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const ensurePasskeyUser = `-- name: EnsurePasskeyUser :one
INSERT INTO passkey_users (user_id, handle)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING handle
`

type EnsurePasskeyUserParams struct {
	UserID int64
	Handle []byte
}

func (q *Queries) EnsurePasskeyUser(ctx context.Context, arg EnsurePasskeyUserParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, ensurePasskeyUser, arg.UserID, arg.Handle)
	var handle []byte
	err := row.Scan(&handle)
	return handle, err
}

const getPasskeyUserByHandle = `-- name: GetPasskeyUserByHandle :one
SELECT users.id, users.public_id, users.name, users.email, users.password_hash, users.created_at, users.updated_at, users.is_admin, passkey_users.handle
FROM passkey_users
JOIN users ON users.id = passkey_users.user_id
WHERE passkey_users.handle = $1
`

type GetPasskeyUserByHandleRow struct {
	User   User
	Handle []byte
}

func (q *Queries) GetPasskeyUserByHandle(ctx context.Context, handle []byte) (GetPasskeyUserByHandleRow, error) {
	row := q.db.QueryRow(ctx, getPasskeyUserByHandle, handle)
	var i GetPasskeyUserByHandleRow
	err := row.Scan(
		&i.User.ID,
		&i.User.PublicID,
		&i.User.Name,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.IsAdmin,
		&i.Handle,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, public_id, user_id, rp_id, credential_id, name, public_key, attestation_type, attestation_format, attestation, extensions, transports, aaguid, attachment, sign_count, flags, created_at, last_used_at FROM passkeys
WHERE user_id = $1 AND rp_id = $2
ORDER BY created_at DESC, id DESC
`

type ListPasskeysParams struct {
	UserID int64
	RpID   string
}

func (q *Queries) ListPasskeys(ctx context.Context, arg ListPasskeysParams) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, arg.UserID, arg.RpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.RpID,
			&i.CredentialID,
			&i.Name,
			&i.PublicKey,
			&i.AttestationType,
			&i.AttestationFormat,
			&i.Attestation,
			&i.Extensions,
			&i.Transports,
			&i.Aaguid,
			&i.Attachment,
			&i.SignCount,
			&i.Flags,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePasskey = `-- name: RenamePasskey :one
UPDATE passkeys
SET name = $1
WHERE public_id = $2 AND user_id = $3
RETURNING id, public_id, user_id, rp_id, credential_id, name, public_key, attestation_type, attestation_format, attestation, extensions, transports, aaguid, attachment, sign_count, flags, created_at, last_used_at
`

type RenamePasskeyParams struct {
	Name     string
	PublicID string
	UserID   int64
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, renamePasskey, arg.Name, arg.PublicID, arg.UserID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RpID,
		&i.CredentialID,
		&i.Name,
		&i.PublicKey,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.Attestation,
		&i.Extensions,
		&i.Transports,
		&i.Aaguid,
		&i.Attachment,
		&i.SignCount,
		&i.Flags,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updatePasskeyUsage = `-- name: UpdatePasskeyUsage :execrows
UPDATE passkeys
SET sign_count = $1, flags = $2, last_used_at = now()
WHERE rp_id = $3 AND credential_id = $4
`

type UpdatePasskeyUsageParams struct {
	SignCount    int64
	Flags        int16
	RpID         string
	CredentialID []byte
}

func (q *Queries) UpdatePasskeyUsage(ctx context.Context, arg UpdatePasskeyUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasskeyUsage,
		arg.SignCount,
		arg.Flags,
		arg.RpID,
		arg.CredentialID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
