// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserBackendQuota = `-- name: CreateUserBackendQuota :execrows
INSERT INTO user_backend_quotas (user_id, backend_id, limit_bytes)
SELECT $1, b.id, $2
FROM storage_backends b
WHERE b.public_id = $3
`

type CreateUserBackendQuotaParams struct {
	UserID          int64
	LimitBytes      pgtype.Int8
	BackendPublicID string
}

func (q *Queries) CreateUserBackendQuota(ctx context.Context, arg CreateUserBackendQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserBackendQuota, arg.UserID, arg.LimitBytes, arg.BackendPublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserDefaultQuota = `-- name: CreateUserDefaultQuota :exec
INSERT INTO user_default_quotas (user_id, limit_bytes)
VALUES ($1, $2)
`

type CreateUserDefaultQuotaParams struct {
	UserID     int64
	LimitBytes pgtype.Int8
}

func (q *Queries) CreateUserDefaultQuota(ctx context.Context, arg CreateUserDefaultQuotaParams) error {
	_, err := q.db.Exec(ctx, createUserDefaultQuota, arg.UserID, arg.LimitBytes)
	return err
}

const deleteUserBackendQuotas = `-- name: DeleteUserBackendQuotas :exec
DELETE FROM user_backend_quotas WHERE user_id = $1
`

func (q *Queries) DeleteUserBackendQuotas(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserBackendQuotas, userID)
	return err
}

const deleteUserDefaultQuota = `-- name: DeleteUserDefaultQuota :exec
DELETE FROM user_default_quotas WHERE user_id = $1
`

func (q *Queries) DeleteUserDefaultQuota(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserDefaultQuota, userID)
	return err
}

const getQuotaSettings = `-- name: GetQuotaSettings :one
SELECT default_limit_bytes FROM quota_settings WHERE id
`

func (q *Queries) GetQuotaSettings(ctx context.Context) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getQuotaSettings)
	var default_limit_bytes pgtype.Int8
	err := row.Scan(&default_limit_bytes)
	return default_limit_bytes, err
}

const getUserBackendQuota = `-- name: GetUserBackendQuota :one
SELECT s.default_limit_bytes AS global_limit_bytes,
       (d.user_id IS NOT NULL)::boolean AS has_user_default, d.limit_bytes AS user_limit_bytes,
       (o.user_id IS NOT NULL)::boolean AS has_backend_override, o.limit_bytes AS backend_limit_bytes,
       (
           SELECT coalesce(sum(bl.size_bytes), 0)
           FROM blobs bl
           JOIN libraries l ON l.id = bl.library_id
           WHERE l.owner_id = $1 AND l.backend_id = $2
       )::bigint AS stored_bytes,
       (
           SELECT coalesce(sum(u.declared_size), 0)
           FROM upload_sessions u
           JOIN libraries l ON l.id = u.library_id
           WHERE u.owner_id = $1 AND l.backend_id = $2
             AND u.state IN ('created', 'uploading', 'uploaded', 'finalizing', 'failed')
       )::bigint AS reserved_bytes
FROM quota_settings s
LEFT JOIN user_default_quotas d ON d.user_id = $1
LEFT JOIN user_backend_quotas o ON o.user_id = $1 AND o.backend_id = $2
WHERE s.id
`

type GetUserBackendQuotaParams struct {
	UserID    int64
	BackendID int64
}

type GetUserBackendQuotaRow struct {
	GlobalLimitBytes   pgtype.Int8
	HasUserDefault     bool
	UserLimitBytes     pgtype.Int8
	HasBackendOverride bool
	BackendLimitBytes  pgtype.Int8
	StoredBytes        int64
	ReservedBytes      int64
}

func (q *Queries) GetUserBackendQuota(ctx context.Context, arg GetUserBackendQuotaParams) (GetUserBackendQuotaRow, error) {
	row := q.db.QueryRow(ctx, getUserBackendQuota, arg.UserID, arg.BackendID)
	var i GetUserBackendQuotaRow
	err := row.Scan(
		&i.GlobalLimitBytes,
		&i.HasUserDefault,
		&i.UserLimitBytes,
		&i.HasBackendOverride,
		&i.BackendLimitBytes,
		&i.StoredBytes,
		&i.ReservedBytes,
	)
	return i, err
}

const listUserBackendQuotas = `-- name: ListUserBackendQuotas :many
SELECT q.user_id, b.public_id AS backend_public_id, q.limit_bytes
FROM user_backend_quotas q
JOIN storage_backends b ON b.id = q.backend_id
ORDER BY q.user_id, lower(b.name), b.id
`

type ListUserBackendQuotasRow struct {
	UserID          int64
	BackendPublicID string
	LimitBytes      pgtype.Int8
}

func (q *Queries) ListUserBackendQuotas(ctx context.Context) ([]ListUserBackendQuotasRow, error) {
	rows, err := q.db.Query(ctx, listUserBackendQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBackendQuotasRow
	for rows.Next() {
		var i ListUserBackendQuotasRow
		if err := rows.Scan(&i.UserID, &i.BackendPublicID, &i.LimitBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDefaultQuotas = `-- name: ListUserDefaultQuotas :many
SELECT user_id, limit_bytes FROM user_default_quotas
`

func (q *Queries) ListUserDefaultQuotas(ctx context.Context) ([]UserDefaultQuota, error) {
	rows, err := q.db.Query(ctx, listUserDefaultQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDefaultQuota
	for rows.Next() {
		var i UserDefaultQuota
		if err := rows.Scan(&i.UserID, &i.LimitBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStorageUsage = `-- name: ListUserStorageUsage :many
SELECT b.public_id, b.name, b.type,
       s.default_limit_bytes AS global_limit_bytes,
       (d.user_id IS NOT NULL)::boolean AS has_user_default, d.limit_bytes AS user_limit_bytes,
       (o.user_id IS NOT NULL)::boolean AS has_backend_override, o.limit_bytes AS backend_limit_bytes,
       (
           SELECT coalesce(sum(bl.size_bytes), 0)
           FROM blobs bl
           JOIN libraries l ON l.id = bl.library_id
           WHERE l.owner_id = $1 AND l.backend_id = b.id
       )::bigint AS stored_bytes,
       (
           SELECT coalesce(sum(u.declared_size), 0)
           FROM upload_sessions u
           JOIN libraries l ON l.id = u.library_id
           WHERE u.owner_id = $1 AND l.backend_id = b.id
             AND u.state IN ('created', 'uploading', 'uploaded', 'finalizing', 'failed')
       )::bigint AS reserved_bytes
FROM storage_backends b
CROSS JOIN quota_settings s
LEFT JOIN user_default_quotas d ON d.user_id = $1
LEFT JOIN user_backend_quotas o ON o.user_id = $1 AND o.backend_id = b.id
WHERE s.id AND EXISTS (SELECT 1 FROM libraries l WHERE l.owner_id = $1 AND l.backend_id = b.id)
ORDER BY lower(b.name), b.id
`

type ListUserStorageUsageRow struct {
	PublicID           string
	Name               string
	Type               string
	GlobalLimitBytes   pgtype.Int8
	HasUserDefault     bool
	UserLimitBytes     pgtype.Int8
	HasBackendOverride bool
	BackendLimitBytes  pgtype.Int8
	StoredBytes        int64
	ReservedBytes      int64
}

func (q *Queries) ListUserStorageUsage(ctx context.Context, userID int64) ([]ListUserStorageUsageRow, error) {
	rows, err := q.db.Query(ctx, listUserStorageUsage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserStorageUsageRow
	for rows.Next() {
		var i ListUserStorageUsageRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.Type,
			&i.GlobalLimitBytes,
			&i.HasUserDefault,
			&i.UserLimitBytes,
			&i.HasBackendOverride,
			&i.BackendLimitBytes,
			&i.StoredBytes,
			&i.ReservedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuotaSettings = `-- name: UpdateQuotaSettings :one
UPDATE quota_settings
SET default_limit_bytes = $1
WHERE id
RETURNING default_limit_bytes
`

func (q *Queries) UpdateQuotaSettings(ctx context.Context, defaultLimitBytes pgtype.Int8) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, updateQuotaSettings, defaultLimitBytes)
	var default_limit_bytes pgtype.Int8
	err := row.Scan(&default_limit_bytes)
	return default_limit_bytes, err
}
