// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLibraryReplication = `-- name: CreateLibraryReplication :one
WITH selected AS (
    SELECT source.id AS source_id, destination.id AS destination_id, source.key_envelope
    FROM libraries source, libraries destination
    WHERE source.public_id = $3
      AND destination.public_id = $4
      AND source.owner_id = $2
      AND destination.owner_id = $2
      AND source.encryption_mode = destination.encryption_mode
      AND source.encryption_format <> 'v2' AND destination.encryption_format <> 'v2'
      AND NOT EXISTS (SELECT 1 FROM nodes n WHERE n.library_id = destination.id AND n.parent_id IS NOT NULL)
      AND NOT EXISTS (
          SELECT 1 FROM upload_sessions upload
          WHERE upload.library_id = destination.id
            AND upload.state IN ('created', 'uploading', 'uploaded', 'finalizing', 'failed')
      )
), prepared AS (
    UPDATE libraries destination
    SET key_envelope = selected.key_envelope, updated_at = now()
    FROM selected
    WHERE destination.id = selected.destination_id
    RETURNING selected.source_id, selected.destination_id
)
INSERT INTO library_replications (public_id, owner_id, source_library_id, destination_library_id)
SELECT $1, $2, source_id, destination_id
FROM prepared
RETURNING id, public_id, owner_id, source_library_id, destination_library_id, state, last_error, last_synced_at, created_at, updated_at
`

type CreateLibraryReplicationParams struct {
	PublicID            string
	OwnerID             int64
	SourcePublicID      string
	DestinationPublicID string
}

func (q *Queries) CreateLibraryReplication(ctx context.Context, arg CreateLibraryReplicationParams) (LibraryReplication, error) {
	row := q.db.QueryRow(ctx, createLibraryReplication,
		arg.PublicID,
		arg.OwnerID,
		arg.SourcePublicID,
		arg.DestinationPublicID,
	)
	var i LibraryReplication
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.SourceLibraryID,
		&i.DestinationLibraryID,
		&i.State,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReplicatedBlob = `-- name: CreateReplicatedBlob :one
INSERT INTO blobs (public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format, encrypted_file_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format, encrypted_file_key, created_at
`

type CreateReplicatedBlobParams struct {
	PublicID         string
	LibraryID        int64
	SizeBytes        int64
	CiphertextSha256 []byte
	DedupFingerprint []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
}

func (q *Queries) CreateReplicatedBlob(ctx context.Context, arg CreateReplicatedBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, createReplicatedBlob,
		arg.PublicID,
		arg.LibraryID,
		arg.SizeBytes,
		arg.CiphertextSha256,
		arg.DedupFingerprint,
		arg.EncryptionFormat,
		arg.EncryptedFileKey,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.SizeBytes,
		&i.CiphertextSha256,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.CreatedAt,
	)
	return i, err
}

const createReplicatedBlobLocation = `-- name: CreateReplicatedBlobLocation :one
INSERT INTO blob_locations (public_id, blob_id, library_id, backend_id, object_key, state, verified_at)
VALUES ($1, $2, $3, $4, $5, 'available', now())
RETURNING id, public_id, blob_id, library_id, backend_id, object_key, state, verified_at, created_at, updated_at
`

type CreateReplicatedBlobLocationParams struct {
	PublicID  string
	BlobID    int64
	LibraryID int64
	BackendID int64
	ObjectKey string
}

func (q *Queries) CreateReplicatedBlobLocation(ctx context.Context, arg CreateReplicatedBlobLocationParams) (BlobLocation, error) {
	row := q.db.QueryRow(ctx, createReplicatedBlobLocation,
		arg.PublicID,
		arg.BlobID,
		arg.LibraryID,
		arg.BackendID,
		arg.ObjectKey,
	)
	var i BlobLocation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BlobID,
		&i.LibraryID,
		&i.BackendID,
		&i.ObjectKey,
		&i.State,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReplicatedFileVersion = `-- name: CreateReplicatedFileVersion :one
INSERT INTO file_versions (public_id, node_id, library_id, ordinal, blob_id, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, node_id, library_id, ordinal, blob_id, size_bytes, content_sha256, restored_from_version_id, created_at
`

type CreateReplicatedFileVersionParams struct {
	PublicID  string
	NodeID    int64
	LibraryID int64
	Ordinal   int64
	BlobID    int64
	SizeBytes int64
}

func (q *Queries) CreateReplicatedFileVersion(ctx context.Context, arg CreateReplicatedFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, createReplicatedFileVersion,
		arg.PublicID,
		arg.NodeID,
		arg.LibraryID,
		arg.Ordinal,
		arg.BlobID,
		arg.SizeBytes,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.NodeID,
		&i.LibraryID,
		&i.Ordinal,
		&i.BlobID,
		&i.SizeBytes,
		&i.ContentSha256,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createReplicatedNode = `-- name: CreateReplicatedNode :one
INSERT INTO nodes (public_id, library_id, parent_id, kind, name, encrypted_name, name_token, revision, trashed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation
`

type CreateReplicatedNodeParams struct {
	PublicID      string
	LibraryID     int64
	ParentID      pgtype.Int8
	Kind          string
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
	Revision      int64
	TrashedAt     pgtype.Timestamptz
}

func (q *Queries) CreateReplicatedNode(ctx context.Context, arg CreateReplicatedNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createReplicatedNode,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
		arg.Revision,
		arg.TrashedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const deleteLibraryReplication = `-- name: DeleteLibraryReplication :execrows
DELETE FROM library_replications WHERE public_id = $1 AND owner_id = $2
`

type DeleteLibraryReplicationParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) DeleteLibraryReplication(ctx context.Context, arg DeleteLibraryReplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLibraryReplication, arg.PublicID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReplicationNodeMapping = `-- name: DeleteReplicationNodeMapping :exec
DELETE FROM replication_nodes WHERE replication_id = $1 AND destination_node_id = $2
`

type DeleteReplicationNodeMappingParams struct {
	ReplicationID     int64
	DestinationNodeID int64
}

func (q *Queries) DeleteReplicationNodeMapping(ctx context.Context, arg DeleteReplicationNodeMappingParams) error {
	_, err := q.db.Exec(ctx, deleteReplicationNodeMapping, arg.ReplicationID, arg.DestinationNodeID)
	return err
}

const getDestinationBlobByFingerprint = `-- name: GetDestinationBlobByFingerprint :one
SELECT id, public_id, library_id, size_bytes, ciphertext_sha256, dedup_fingerprint, encryption_format, encrypted_file_key, created_at FROM blobs WHERE library_id = $1 AND dedup_fingerprint = $2
`

type GetDestinationBlobByFingerprintParams struct {
	LibraryID        int64
	DedupFingerprint []byte
}

func (q *Queries) GetDestinationBlobByFingerprint(ctx context.Context, arg GetDestinationBlobByFingerprintParams) (Blob, error) {
	row := q.db.QueryRow(ctx, getDestinationBlobByFingerprint, arg.LibraryID, arg.DedupFingerprint)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.SizeBytes,
		&i.CiphertextSha256,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.CreatedAt,
	)
	return i, err
}

const getReplicationByID = `-- name: GetReplicationByID :one
SELECT r.id, r.public_id, r.owner_id, r.source_library_id, r.destination_library_id, r.state, r.last_error, r.last_synced_at, r.created_at, r.updated_at, source.public_id AS source_public_id, source.root_node_id AS source_root_node_id,
       destination.public_id AS destination_public_id, destination.root_node_id AS destination_root_node_id,
       source.backend_id AS source_backend_id, source_backend.public_id AS source_backend_public_id,
       destination.backend_id AS destination_backend_id, destination_backend.public_id AS destination_backend_public_id
FROM library_replications r
JOIN libraries source ON source.id = r.source_library_id
JOIN libraries destination ON destination.id = r.destination_library_id
JOIN storage_backends source_backend ON source_backend.id = source.backend_id
JOIN storage_backends destination_backend ON destination_backend.id = destination.backend_id
WHERE r.id = $1
`

type GetReplicationByIDRow struct {
	ID                         int64
	PublicID                   string
	OwnerID                    int64
	SourceLibraryID            int64
	DestinationLibraryID       int64
	State                      string
	LastError                  pgtype.Text
	LastSyncedAt               pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	SourcePublicID             string
	SourceRootNodeID           int64
	DestinationPublicID        string
	DestinationRootNodeID      int64
	SourceBackendID            int64
	SourceBackendPublicID      string
	DestinationBackendID       int64
	DestinationBackendPublicID string
}

func (q *Queries) GetReplicationByID(ctx context.Context, id int64) (GetReplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getReplicationByID, id)
	var i GetReplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.SourceLibraryID,
		&i.DestinationLibraryID,
		&i.State,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourcePublicID,
		&i.SourceRootNodeID,
		&i.DestinationPublicID,
		&i.DestinationRootNodeID,
		&i.SourceBackendID,
		&i.SourceBackendPublicID,
		&i.DestinationBackendID,
		&i.DestinationBackendPublicID,
	)
	return i, err
}

const getReplicationByPublicIDAndOwner = `-- name: GetReplicationByPublicIDAndOwner :one
SELECT r.id, r.public_id, r.owner_id, r.source_library_id, r.destination_library_id, r.state, r.last_error, r.last_synced_at, r.created_at, r.updated_at, source.public_id AS source_public_id, source.name AS source_name,
       destination.public_id AS destination_public_id, destination.name AS destination_name,
       source.encryption_mode AS source_encryption_mode,
       destination.encryption_mode AS destination_encryption_mode,
       source.backend_id AS source_backend_id,
       destination.backend_id AS destination_backend_id
FROM library_replications r
JOIN libraries source ON source.id = r.source_library_id
JOIN libraries destination ON destination.id = r.destination_library_id
WHERE r.public_id = $1 AND r.owner_id = $2
`

type GetReplicationByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

type GetReplicationByPublicIDAndOwnerRow struct {
	ID                        int64
	PublicID                  string
	OwnerID                   int64
	SourceLibraryID           int64
	DestinationLibraryID      int64
	State                     string
	LastError                 pgtype.Text
	LastSyncedAt              pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	SourcePublicID            string
	SourceName                pgtype.Text
	DestinationPublicID       string
	DestinationName           pgtype.Text
	SourceEncryptionMode      string
	DestinationEncryptionMode string
	SourceBackendID           int64
	DestinationBackendID      int64
}

func (q *Queries) GetReplicationByPublicIDAndOwner(ctx context.Context, arg GetReplicationByPublicIDAndOwnerParams) (GetReplicationByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getReplicationByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i GetReplicationByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.SourceLibraryID,
		&i.DestinationLibraryID,
		&i.State,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourcePublicID,
		&i.SourceName,
		&i.DestinationPublicID,
		&i.DestinationName,
		&i.SourceEncryptionMode,
		&i.DestinationEncryptionMode,
		&i.SourceBackendID,
		&i.DestinationBackendID,
	)
	return i, err
}

const getReplicationDestinationVersion = `-- name: GetReplicationDestinationVersion :one
SELECT source_version.public_id AS source_version_public_id
FROM replication_nodes mapping
JOIN nodes destination_node ON destination_node.id = mapping.destination_node_id
JOIN file_versions destination_version ON destination_version.id = destination_node.current_version_id
JOIN file_versions source_version ON source_version.node_id = mapping.source_node_id
WHERE mapping.replication_id = $1 AND mapping.source_node_id = $2
  AND source_version.ordinal = destination_version.ordinal
`

type GetReplicationDestinationVersionParams struct {
	ReplicationID int64
	SourceNodeID  int64
}

func (q *Queries) GetReplicationDestinationVersion(ctx context.Context, arg GetReplicationDestinationVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, getReplicationDestinationVersion, arg.ReplicationID, arg.SourceNodeID)
	var source_version_public_id string
	err := row.Scan(&source_version_public_id)
	return source_version_public_id, err
}

const isLibraryReplicationDestination = `-- name: IsLibraryReplicationDestination :one
SELECT EXISTS (
    SELECT 1 FROM library_replications r
    JOIN libraries l ON l.id = r.destination_library_id
    WHERE l.public_id = $1 AND r.owner_id = $2
)
`

type IsLibraryReplicationDestinationParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) IsLibraryReplicationDestination(ctx context.Context, arg IsLibraryReplicationDestinationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLibraryReplicationDestination, arg.PublicID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isNodeInReplicationDestination = `-- name: IsNodeInReplicationDestination :one
SELECT EXISTS (
    SELECT 1 FROM nodes n
    JOIN library_replications r ON r.destination_library_id = n.library_id
    WHERE n.public_id = $1 AND r.owner_id = $2
)
`

type IsNodeInReplicationDestinationParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) IsNodeInReplicationDestination(ctx context.Context, arg IsNodeInReplicationDestinationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNodeInReplicationDestination, arg.PublicID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLibraryReplicationsByOwner = `-- name: ListLibraryReplicationsByOwner :many
SELECT r.id, r.public_id, r.owner_id, r.source_library_id, r.destination_library_id, r.state, r.last_error, r.last_synced_at, r.created_at, r.updated_at, source.public_id AS source_public_id, source.name AS source_name,
       destination.public_id AS destination_public_id, destination.name AS destination_name
FROM library_replications r
JOIN libraries source ON source.id = r.source_library_id
JOIN libraries destination ON destination.id = r.destination_library_id
WHERE r.owner_id = $1
ORDER BY source.name, r.id
`

type ListLibraryReplicationsByOwnerRow struct {
	ID                   int64
	PublicID             string
	OwnerID              int64
	SourceLibraryID      int64
	DestinationLibraryID int64
	State                string
	LastError            pgtype.Text
	LastSyncedAt         pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	SourcePublicID       string
	SourceName           pgtype.Text
	DestinationPublicID  string
	DestinationName      pgtype.Text
}

func (q *Queries) ListLibraryReplicationsByOwner(ctx context.Context, ownerID int64) ([]ListLibraryReplicationsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLibraryReplicationsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryReplicationsByOwnerRow
	for rows.Next() {
		var i ListLibraryReplicationsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OwnerID,
			&i.SourceLibraryID,
			&i.DestinationLibraryID,
			&i.State,
			&i.LastError,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourcePublicID,
			&i.SourceName,
			&i.DestinationPublicID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemovedReplicationNodes = `-- name: ListRemovedReplicationNodes :many
SELECT mapping.destination_node_id
FROM replication_nodes mapping
LEFT JOIN nodes source ON source.id = mapping.source_node_id
WHERE mapping.replication_id = $1 AND (source.id IS NULL OR source.library_id <> $2)
`

type ListRemovedReplicationNodesParams struct {
	ReplicationID int64
	LibraryID     int64
}

func (q *Queries) ListRemovedReplicationNodes(ctx context.Context, arg ListRemovedReplicationNodesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRemovedReplicationNodes, arg.ReplicationID, arg.LibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var destination_node_id int64
		if err := rows.Scan(&destination_node_id); err != nil {
			return nil, err
		}
		items = append(items, destination_node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicationIDs = `-- name: ListReplicationIDs :many
SELECT id FROM library_replications ORDER BY id
`

func (q *Queries) ListReplicationIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listReplicationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicationSourceNodes = `-- name: ListReplicationSourceNodes :many
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at, n.key_epoch, n.metadata_revision, n.encrypted_metadata, n.metadata_signature, n.current_version_pointer, n.current_version_signature, n.visible_encryption_generation, parent_map.destination_node_id AS destination_parent_id,
       mapped.destination_node_id, current_version.public_id AS version_public_id,
       current_version.size_bytes, blob.id AS blob_id, blob.public_id AS blob_public_id,
       blob.size_bytes AS stored_size_bytes, blob.ciphertext_sha256, blob.dedup_fingerprint,
       blob.encryption_format, blob.encrypted_file_key, location.object_key
       , destination_blob.dedup_fingerprint AS destination_dedup_fingerprint
FROM nodes n
LEFT JOIN replication_nodes mapped ON mapped.replication_id = $1 AND mapped.source_node_id = n.id
LEFT JOIN replication_nodes parent_map ON parent_map.replication_id = $1 AND parent_map.source_node_id = n.parent_id
LEFT JOIN nodes destination_node ON destination_node.id = mapped.destination_node_id
LEFT JOIN file_versions destination_version ON destination_version.id = destination_node.current_version_id
LEFT JOIN blobs destination_blob ON destination_blob.id = destination_version.blob_id
LEFT JOIN file_versions current_version ON current_version.id = n.current_version_id
LEFT JOIN blobs blob ON blob.id = current_version.blob_id
LEFT JOIN blob_locations location ON location.blob_id = blob.id AND location.state = 'available'
WHERE n.library_id = $2 AND n.parent_id IS NOT NULL
ORDER BY n.id
`

type ListReplicationSourceNodesParams struct {
	ReplicationID   int64
	SourceLibraryID int64
}

type ListReplicationSourceNodesRow struct {
	ID                          int64
	PublicID                    string
	LibraryID                   int64
	ParentID                    pgtype.Int8
	Kind                        string
	Name                        pgtype.Text
	EncryptedName               []byte
	NameToken                   []byte
	CurrentVersionID            pgtype.Int8
	Revision                    int64
	TrashedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	KeyEpoch                    int64
	MetadataRevision            int64
	EncryptedMetadata           []byte
	MetadataSignature           []byte
	CurrentVersionPointer       []byte
	CurrentVersionSignature     []byte
	VisibleEncryptionGeneration int64
	DestinationParentID         pgtype.Int8
	DestinationNodeID           pgtype.Int8
	VersionPublicID             pgtype.Text
	SizeBytes                   pgtype.Int8
	BlobID                      pgtype.Int8
	BlobPublicID                pgtype.Text
	StoredSizeBytes             pgtype.Int8
	CiphertextSha256            []byte
	DedupFingerprint            []byte
	EncryptionFormat            pgtype.Text
	EncryptedFileKey            []byte
	ObjectKey                   pgtype.Text
	DestinationDedupFingerprint []byte
}

func (q *Queries) ListReplicationSourceNodes(ctx context.Context, arg ListReplicationSourceNodesParams) ([]ListReplicationSourceNodesRow, error) {
	rows, err := q.db.Query(ctx, listReplicationSourceNodes, arg.ReplicationID, arg.SourceLibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplicationSourceNodesRow
	for rows.Next() {
		var i ListReplicationSourceNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.CurrentVersionID,
			&i.Revision,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeyEpoch,
			&i.MetadataRevision,
			&i.EncryptedMetadata,
			&i.MetadataSignature,
			&i.CurrentVersionPointer,
			&i.CurrentVersionSignature,
			&i.VisibleEncryptionGeneration,
			&i.DestinationParentID,
			&i.DestinationNodeID,
			&i.VersionPublicID,
			&i.SizeBytes,
			&i.BlobID,
			&i.BlobPublicID,
			&i.StoredSizeBytes,
			&i.CiphertextSha256,
			&i.DedupFingerprint,
			&i.EncryptionFormat,
			&i.EncryptedFileKey,
			&i.ObjectKey,
			&i.DestinationDedupFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLibraryReplication = `-- name: LockLibraryReplication :one
SELECT id, public_id, owner_id, source_library_id, destination_library_id, state, last_error, last_synced_at, created_at, updated_at FROM library_replications WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockLibraryReplication(ctx context.Context, id int64) (LibraryReplication, error) {
	row := q.db.QueryRow(ctx, lockLibraryReplication, id)
	var i LibraryReplication
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.SourceLibraryID,
		&i.DestinationLibraryID,
		&i.State,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mapReplicationNode = `-- name: MapReplicationNode :exec
INSERT INTO replication_nodes (replication_id, source_node_id, destination_node_id)
VALUES ($1, $2, $3)
`

type MapReplicationNodeParams struct {
	ReplicationID     int64
	SourceNodeID      int64
	DestinationNodeID int64
}

func (q *Queries) MapReplicationNode(ctx context.Context, arg MapReplicationNodeParams) error {
	_, err := q.db.Exec(ctx, mapReplicationNode, arg.ReplicationID, arg.SourceNodeID, arg.DestinationNodeID)
	return err
}

const markReplicationFailed = `-- name: MarkReplicationFailed :exec
UPDATE library_replications SET state = 'failed', last_error = $2, updated_at = now() WHERE id = $1
`

type MarkReplicationFailedParams struct {
	ID        int64
	LastError pgtype.Text
}

func (q *Queries) MarkReplicationFailed(ctx context.Context, arg MarkReplicationFailedParams) error {
	_, err := q.db.Exec(ctx, markReplicationFailed, arg.ID, arg.LastError)
	return err
}

const markReplicationReady = `-- name: MarkReplicationReady :exec
UPDATE library_replications SET state = 'ready', last_error = NULL, last_synced_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkReplicationReady(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReplicationReady, id)
	return err
}

const markReplicationSyncing = `-- name: MarkReplicationSyncing :exec
UPDATE library_replications SET state = 'syncing', last_error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkReplicationSyncing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReplicationSyncing, id)
	return err
}

const setReplicatedNodeVersion = `-- name: SetReplicatedNodeVersion :exec
UPDATE nodes SET current_version_id = $2, updated_at = now() WHERE id = $1
`

type SetReplicatedNodeVersionParams struct {
	ID               int64
	CurrentVersionID pgtype.Int8
}

func (q *Queries) SetReplicatedNodeVersion(ctx context.Context, arg SetReplicatedNodeVersionParams) error {
	_, err := q.db.Exec(ctx, setReplicatedNodeVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const trashReplicatedNode = `-- name: TrashReplicatedNode :exec
UPDATE nodes SET trashed_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TrashReplicatedNode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, trashReplicatedNode, id)
	return err
}

const updateReplicatedNode = `-- name: UpdateReplicatedNode :exec
UPDATE nodes SET parent_id = $2, name = $3, encrypted_name = $4, name_token = $5,
    revision = $6, trashed_at = $7, updated_at = now()
WHERE id = $1
`

type UpdateReplicatedNodeParams struct {
	ID            int64
	ParentID      pgtype.Int8
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
	Revision      int64
	TrashedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateReplicatedNode(ctx context.Context, arg UpdateReplicatedNodeParams) error {
	_, err := q.db.Exec(ctx, updateReplicatedNode,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
		arg.Revision,
		arg.TrashedAt,
	)
	return err
}
