// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, public_id, user_id, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	TokenHash []byte
	PublicID  string
	UserID    int64
	UserAgent string
	IpAddress *netip.Addr
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.PublicID,
		arg.UserID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND token_hash <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID           int64
	CurrentTokenHash []byte
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.CurrentTokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :one
DELETE FROM sessions WHERE public_id = $1 AND user_id = $2
RETURNING token_hash
`

type DeleteUserSessionParams struct {
	PublicID string
	UserID   int64
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteUserSession, arg.PublicID, arg.UserID)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, public_id, user_id, user_agent, ip_address, created_at, expires_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.PublicID,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.public_id, users.name, users.email, users.password_hash, users.created_at, users.updated_at, users.is_admin FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    public_id,
    user_agent,
    ip_address,
    created_at,
    (token_hash = $1::bytea)::boolean AS current
FROM sessions
WHERE user_id = $2 AND expires_at > now()
ORDER BY current DESC, created_at DESC
`

type ListUserSessionsParams struct {
	CurrentTokenHash []byte
	UserID           int64
}

type ListUserSessionsRow struct {
	PublicID  string
	UserAgent string
	IpAddress *netip.Addr
	CreatedAt pgtype.Timestamptz
	Current   bool
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.CurrentTokenHash, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
DELETE FROM sessions WHERE token_hash = $1
RETURNING user_id, public_id
`

type RevokeSessionRow struct {
	UserID   int64
	PublicID string
}

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, tokenHash)
	var i RevokeSessionRow
	err := row.Scan(&i.UserID, &i.PublicID)
	return i, err
}
