// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
	UserAgent string
	IpAddress *netip.Addr
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_id, user_agent, ip_address, created_at, expires_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.public_id, users.name, users.email, users.password_hash, users.created_at, users.updated_at, users.is_admin FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
