// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_backends.sql

package db

import (
	"context"
)

const createStorageBackend = `-- name: CreateStorageBackend :one
INSERT INTO storage_backends (public_id, name, type, config, encrypted_secrets, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at
`

type CreateStorageBackendParams struct {
	PublicID         string
	Name             string
	Type             string
	Config           []byte
	EncryptedSecrets string
	Enabled          bool
}

func (q *Queries) CreateStorageBackend(ctx context.Context, arg CreateStorageBackendParams) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, createStorageBackend,
		arg.PublicID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.EncryptedSecrets,
		arg.Enabled,
	)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EncryptedSecrets,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStorageBackend = `-- name: DeleteStorageBackend :execrows
DELETE FROM storage_backends WHERE public_id = $1
`

func (q *Queries) DeleteStorageBackend(ctx context.Context, publicID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStorageBackend, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStorageBackendByPublicID = `-- name: GetStorageBackendByPublicID :one
SELECT id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at FROM storage_backends WHERE public_id = $1
`

func (q *Queries) GetStorageBackendByPublicID(ctx context.Context, publicID string) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, getStorageBackendByPublicID, publicID)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EncryptedSecrets,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageBackends = `-- name: ListStorageBackends :many
SELECT id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at FROM storage_backends ORDER BY lower(name), id
`

func (q *Queries) ListStorageBackends(ctx context.Context) ([]StorageBackend, error) {
	rows, err := q.db.Query(ctx, listStorageBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageBackend
	for rows.Next() {
		var i StorageBackend
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EncryptedSecrets,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStorageBackendByPublicID = `-- name: LockStorageBackendByPublicID :one
SELECT id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at FROM storage_backends WHERE public_id = $1 FOR UPDATE
`

func (q *Queries) LockStorageBackendByPublicID(ctx context.Context, publicID string) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, lockStorageBackendByPublicID, publicID)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EncryptedSecrets,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStorageBackend = `-- name: UpdateStorageBackend :one
UPDATE storage_backends
SET name = $2, config = $3, encrypted_secrets = $4, enabled = $5, updated_at = now()
WHERE public_id = $1
RETURNING id, public_id, name, type, config, encrypted_secrets, enabled, created_at, updated_at
`

type UpdateStorageBackendParams struct {
	PublicID         string
	Name             string
	Config           []byte
	EncryptedSecrets string
	Enabled          bool
}

func (q *Queries) UpdateStorageBackend(ctx context.Context, arg UpdateStorageBackendParams) (StorageBackend, error) {
	row := q.db.QueryRow(ctx, updateStorageBackend,
		arg.PublicID,
		arg.Name,
		arg.Config,
		arg.EncryptedSecrets,
		arg.Enabled,
	)
	var i StorageBackend
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.EncryptedSecrets,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
