// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFileTag = `-- name: AddFileTag :execrows
INSERT INTO file_tags (node_id, tag_id, library_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddFileTagParams struct {
	NodeID    int64
	TagID     int64
	LibraryID int64
}

func (q *Queries) AddFileTag(ctx context.Context, arg AddFileTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFileTag, arg.NodeID, arg.TagID, arg.LibraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (public_id, library_id, name, encrypted_name, name_token, color, encrypted_color)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, library_id, name, encrypted_name, name_token, color, encrypted_color, created_at, updated_at
`

type CreateTagParams struct {
	PublicID       string
	LibraryID      int64
	Name           pgtype.Text
	EncryptedName  []byte
	NameToken      []byte
	Color          pgtype.Text
	EncryptedColor []byte
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.PublicID,
		arg.LibraryID,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
		arg.Color,
		arg.EncryptedColor,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.Color,
		&i.EncryptedColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTagByPublicIDAndOwner = `-- name: GetTagByPublicIDAndOwner :one
SELECT t.id, t.public_id, t.library_id, t.name, t.encrypted_name, t.name_token, t.color, t.encrypted_color, t.created_at, t.updated_at
FROM tags t
JOIN libraries l ON l.id = t.library_id
WHERE t.public_id = $1 AND l.owner_id = $2
`

type GetTagByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) GetTagByPublicIDAndOwner(ctx context.Context, arg GetTagByPublicIDAndOwnerParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.Color,
		&i.EncryptedColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTagsByLibrary = `-- name: ListTagsByLibrary :many
SELECT id, public_id, library_id, name, encrypted_name, name_token, color, encrypted_color, created_at, updated_at FROM tags WHERE library_id = $1 ORDER BY id
`

func (q *Queries) ListTagsByLibrary(ctx context.Context, libraryID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.Color,
			&i.EncryptedColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForNodes = `-- name: ListTagsForNodes :many
SELECT ft.node_id, t.id, t.public_id, t.library_id, t.name, t.encrypted_name, t.name_token, t.color, t.encrypted_color, t.created_at, t.updated_at
FROM file_tags ft
JOIN tags t ON t.id = ft.tag_id
WHERE ft.node_id = ANY($1::bigint[])
ORDER BY ft.node_id, t.id
`

type ListTagsForNodesRow struct {
	NodeID         int64
	ID             int64
	PublicID       string
	LibraryID      int64
	Name           pgtype.Text
	EncryptedName  []byte
	NameToken      []byte
	Color          pgtype.Text
	EncryptedColor []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListTagsForNodes(ctx context.Context, nodeIds []int64) ([]ListTagsForNodesRow, error) {
	rows, err := q.db.Query(ctx, listTagsForNodes, nodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForNodesRow
	for rows.Next() {
		var i ListTagsForNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.Color,
			&i.EncryptedColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFileTag = `-- name: RemoveFileTag :execrows
DELETE FROM file_tags WHERE node_id = $1 AND tag_id = $2
`

type RemoveFileTagParams struct {
	NodeID int64
	TagID  int64
}

func (q *Queries) RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFileTag, arg.NodeID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, encrypted_name = $3, name_token = $4, color = $5, encrypted_color = $6, updated_at = now()
WHERE id = $1
RETURNING id, public_id, library_id, name, encrypted_name, name_token, color, encrypted_color, created_at, updated_at
`

type UpdateTagParams struct {
	ID             int64
	Name           pgtype.Text
	EncryptedName  []byte
	NameToken      []byte
	Color          pgtype.Text
	EncryptedColor []byte
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
		arg.Color,
		arg.EncryptedColor,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.Color,
		&i.EncryptedColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
