// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trash.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSubtreeCurrentVersion = `-- name: ClearSubtreeCurrentVersion :exec
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
UPDATE nodes SET current_version_id = NULL WHERE nodes.id IN (SELECT subtree.id FROM subtree)
`

func (q *Queries) ClearSubtreeCurrentVersion(ctx context.Context, nodeID int64) error {
	_, err := q.db.Exec(ctx, clearSubtreeCurrentVersion, nodeID)
	return err
}

const countActiveUploadSessionsInSubtree = `-- name: CountActiveUploadSessionsInSubtree :one
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
SELECT count(*)::bigint FROM upload_sessions
WHERE upload_sessions.parent_id IN (SELECT subtree.id FROM subtree)
  AND upload_sessions.state IN ('created', 'uploading', 'uploaded', 'finalizing')
`

func (q *Queries) CountActiveUploadSessionsInSubtree(ctx context.Context, nodeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUploadSessionsInSubtree, nodeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteSubtreeFileVersions = `-- name: DeleteSubtreeFileVersions :many
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
DELETE FROM file_versions WHERE file_versions.node_id IN (SELECT subtree.id FROM subtree)
RETURNING blob_id
`

func (q *Queries) DeleteSubtreeFileVersions(ctx context.Context, nodeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteSubtreeFileVersions, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var blob_id int64
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSubtreeNodes = `-- name: DeleteSubtreeNodes :execrows
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
DELETE FROM nodes WHERE nodes.id IN (SELECT subtree.id FROM subtree)
`

func (q *Queries) DeleteSubtreeNodes(ctx context.Context, nodeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubtreeNodes, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLibraryRootNodeID = `-- name: GetLibraryRootNodeID :one
SELECT root_node_id FROM libraries WHERE id = $1
`

func (q *Queries) GetLibraryRootNodeID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLibraryRootNodeID, id)
	var root_node_id int64
	err := row.Scan(&root_node_id)
	return root_node_id, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredTrashRoots = `-- name: ListExpiredTrashRoots :many
SELECT n.id, n.public_id
FROM nodes n
JOIN nodes parent ON parent.id = n.parent_id
WHERE n.trashed_at IS NOT NULL AND n.trashed_at < $1
  AND parent.trashed_at IS NULL
ORDER BY n.id
LIMIT $2
`

type ListExpiredTrashRootsParams struct {
	Cutoff    pgtype.Timestamptz
	PageLimit int32
}

type ListExpiredTrashRootsRow struct {
	ID       int64
	PublicID string
}

func (q *Queries) ListExpiredTrashRoots(ctx context.Context, arg ListExpiredTrashRootsParams) ([]ListExpiredTrashRootsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTrashRoots, arg.Cutoff, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredTrashRootsRow
	for rows.Next() {
		var i ListExpiredTrashRootsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashRootsByOwner = `-- name: ListTrashRootsByOwner :many
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at, l.public_id AS library_public_id, l.name AS library_name,
       l.encryption_mode AS library_encryption_mode, parent.public_id AS parent_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
JOIN nodes parent ON parent.id = n.parent_id
WHERE l.owner_id = $1
  AND n.trashed_at IS NOT NULL AND parent.trashed_at IS NULL
  AND n.id > $2
ORDER BY n.id
LIMIT $3
`

type ListTrashRootsByOwnerParams struct {
	OwnerID   int64
	AfterID   int64
	PageLimit int32
}

type ListTrashRootsByOwnerRow struct {
	ID                    int64
	PublicID              string
	LibraryID             int64
	ParentID              pgtype.Int8
	Kind                  string
	Name                  pgtype.Text
	EncryptedName         []byte
	NameToken             []byte
	CurrentVersionID      pgtype.Int8
	Revision              int64
	TrashedAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	LibraryPublicID       string
	LibraryName           string
	LibraryEncryptionMode string
	ParentPublicID        string
}

func (q *Queries) ListTrashRootsByOwner(ctx context.Context, arg ListTrashRootsByOwnerParams) ([]ListTrashRootsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTrashRootsByOwner, arg.OwnerID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashRootsByOwnerRow
	for rows.Next() {
		var i ListTrashRootsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.LibraryID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.EncryptedName,
			&i.NameToken,
			&i.CurrentVersionID,
			&i.Revision,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryPublicID,
			&i.LibraryName,
			&i.LibraryEncryptionMode,
			&i.ParentPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepareUploadSessionsForSubtreeRemoval = `-- name: PrepareUploadSessionsForSubtreeRemoval :exec
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $2
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
UPDATE upload_sessions
SET parent_id = CASE WHEN upload_sessions.parent_id IN (SELECT subtree.id FROM subtree) THEN $1 ELSE upload_sessions.parent_id END,
    target_node_id = CASE WHEN upload_sessions.target_node_id IN (SELECT subtree.id FROM subtree) THEN NULL ELSE upload_sessions.target_node_id END,
    published_node_id = CASE WHEN upload_sessions.published_node_id IN (SELECT subtree.id FROM subtree) THEN NULL ELSE upload_sessions.published_node_id END,
    published_version_id = CASE WHEN upload_sessions.published_node_id IN (SELECT subtree.id FROM subtree) THEN NULL ELSE upload_sessions.published_version_id END,
    updated_at = now()
WHERE upload_sessions.parent_id IN (SELECT subtree.id FROM subtree)
   OR upload_sessions.target_node_id IN (SELECT subtree.id FROM subtree)
   OR upload_sessions.published_node_id IN (SELECT subtree.id FROM subtree)
`

type PrepareUploadSessionsForSubtreeRemovalParams struct {
	RootNodeID int64
	NodeID     int64
}

func (q *Queries) PrepareUploadSessionsForSubtreeRemoval(ctx context.Context, arg PrepareUploadSessionsForSubtreeRemovalParams) error {
	_, err := q.db.Exec(ctx, prepareUploadSessionsForSubtreeRemoval, arg.RootNodeID, arg.NodeID)
	return err
}

const restoreNodeSubtree = `-- name: RestoreNodeSubtree :execrows
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
UPDATE nodes SET trashed_at = NULL, updated_at = now()
WHERE nodes.id IN (SELECT subtree.id FROM subtree) AND nodes.trashed_at IS NOT NULL
`

func (q *Queries) RestoreNodeSubtree(ctx context.Context, nodeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreNodeSubtree, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trashNodeSubtree = `-- name: TrashNodeSubtree :execrows
WITH RECURSIVE subtree AS (
    SELECT n.id FROM nodes n WHERE n.id = $1
    UNION ALL
    SELECT child.id FROM nodes child JOIN subtree parent ON child.parent_id = parent.id
)
UPDATE nodes SET trashed_at = COALESCE(nodes.trashed_at, now()), updated_at = now()
WHERE nodes.id IN (SELECT subtree.id FROM subtree)
`

func (q *Queries) TrashNodeSubtree(ctx context.Context, nodeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, trashNodeSubtree, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
