// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads_v2.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileVersionKey = `-- name: CreateFileVersionKey :exec
INSERT INTO file_version_keys (
    version_id, node_id, node_epoch, generation, content_id, encrypted_content_key, signed_manifest,
    manifest_signature
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateFileVersionKeyParams struct {
	VersionID           int64
	NodeID              int64
	NodeEpoch           int64
	Generation          int64
	ContentID           []byte
	EncryptedContentKey []byte
	SignedManifest      []byte
	ManifestSignature   []byte
}

func (q *Queries) CreateFileVersionKey(ctx context.Context, arg CreateFileVersionKeyParams) error {
	_, err := q.db.Exec(ctx, createFileVersionKey,
		arg.VersionID,
		arg.NodeID,
		arg.NodeEpoch,
		arg.Generation,
		arg.ContentID,
		arg.EncryptedContentKey,
		arg.SignedManifest,
		arg.ManifestSignature,
	)
	return err
}

const createV2UploadFileNode = `-- name: CreateV2UploadFileNode :one
INSERT INTO nodes (
    public_id, library_id, parent_id, kind, name_token, encrypted_metadata, metadata_signature,
    key_epoch, metadata_revision
) VALUES ($1, $2, $3, 'file', $4, $5, $6, 1, 1)
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation
`

type CreateV2UploadFileNodeParams struct {
	PublicID          string
	LibraryID         int64
	ParentID          pgtype.Int8
	NameToken         []byte
	EncryptedMetadata []byte
	MetadataSignature []byte
}

func (q *Queries) CreateV2UploadFileNode(ctx context.Context, arg CreateV2UploadFileNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createV2UploadFileNode,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.NameToken,
		arg.EncryptedMetadata,
		arg.MetadataSignature,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const createV2UploadSession = `-- name: CreateV2UploadSession :one
INSERT INTO upload_sessions (
    public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name_token,
    node_public_id, encrypted_metadata, metadata_signature, parent_envelope, parent_envelope_signature,
    declared_size, staging_key, destination_key, state, encryption_format, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15, 'created', 'stocat-framed-v2',
    $16
)
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at, node_public_id, encrypted_metadata, metadata_signature, parent_envelope, parent_envelope_signature, file_key_record, manifest_record, manifest_signature, current_version_record, current_version_signature
`

type CreateV2UploadSessionParams struct {
	PublicID                string
	OwnerID                 int64
	LibraryID               int64
	ParentID                int64
	TargetNodeID            pgtype.Int8
	ExpectedRevision        pgtype.Int8
	NameToken               []byte
	NodePublicID            pgtype.Text
	EncryptedMetadata       []byte
	MetadataSignature       []byte
	ParentEnvelope          []byte
	ParentEnvelopeSignature []byte
	DeclaredSize            int64
	StagingKey              string
	DestinationKey          string
	ExpiresAt               pgtype.Timestamptz
}

func (q *Queries) CreateV2UploadSession(ctx context.Context, arg CreateV2UploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createV2UploadSession,
		arg.PublicID,
		arg.OwnerID,
		arg.LibraryID,
		arg.ParentID,
		arg.TargetNodeID,
		arg.ExpectedRevision,
		arg.NameToken,
		arg.NodePublicID,
		arg.EncryptedMetadata,
		arg.MetadataSignature,
		arg.ParentEnvelope,
		arg.ParentEnvelopeSignature,
		arg.DeclaredSize,
		arg.StagingKey,
		arg.DestinationKey,
		arg.ExpiresAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NodePublicID,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.ParentEnvelope,
		&i.ParentEnvelopeSignature,
		&i.FileKeyRecord,
		&i.ManifestRecord,
		&i.ManifestSignature,
		&i.CurrentVersionRecord,
		&i.CurrentVersionSignature,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at, key_epoch, metadata_revision, encrypted_metadata, metadata_signature, current_version_pointer, current_version_signature, visible_encryption_generation FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
	)
	return i, err
}

const lockV2LibraryForUpload = `-- name: LockV2LibraryForUpload :one
SELECT l.id, l.public_id, l.backend_id, b.name AS backend_name
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
WHERE l.public_id = $1 AND l.owner_id = $2 AND l.encryption_format = 'v2' AND b.enabled = true
FOR UPDATE OF l
`

type LockV2LibraryForUploadParams struct {
	PublicID string
	OwnerID  int64
}

type LockV2LibraryForUploadRow struct {
	ID          int64
	PublicID    string
	BackendID   int64
	BackendName string
}

func (q *Queries) LockV2LibraryForUpload(ctx context.Context, arg LockV2LibraryForUploadParams) (LockV2LibraryForUploadRow, error) {
	row := q.db.QueryRow(ctx, lockV2LibraryForUpload, arg.PublicID, arg.OwnerID)
	var i LockV2LibraryForUploadRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BackendID,
		&i.BackendName,
	)
	return i, err
}

const setV2CurrentVersion = `-- name: SetV2CurrentVersion :one
UPDATE nodes
SET current_version_id = $1, current_version_pointer = $2,
    current_version_signature = $3, revision = revision + 1, updated_at = now()
WHERE id = $4 AND kind = 'file'
RETURNING revision
`

type SetV2CurrentVersionParams struct {
	CurrentVersionID        pgtype.Int8
	CurrentVersionPointer   []byte
	CurrentVersionSignature []byte
	ID                      int64
}

func (q *Queries) SetV2CurrentVersion(ctx context.Context, arg SetV2CurrentVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, setV2CurrentVersion,
		arg.CurrentVersionID,
		arg.CurrentVersionPointer,
		arg.CurrentVersionSignature,
		arg.ID,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const setV2UploadFinalizing = `-- name: SetV2UploadFinalizing :one
UPDATE upload_sessions
SET file_key_record = $1, manifest_record = $2,
    manifest_signature = $3, current_version_record = $4,
    current_version_signature = $5,
    state = 'finalizing', failure_code = NULL, failure_message = NULL, updated_at = now()
WHERE id = $6 AND state = 'uploaded' AND upload_offset = declared_size
  AND encryption_format = 'stocat-framed-v2'
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at, node_public_id, encrypted_metadata, metadata_signature, parent_envelope, parent_envelope_signature, file_key_record, manifest_record, manifest_signature, current_version_record, current_version_signature
`

type SetV2UploadFinalizingParams struct {
	FileKeyRecord           []byte
	ManifestRecord          []byte
	ManifestSignature       []byte
	CurrentVersionRecord    []byte
	CurrentVersionSignature []byte
	ID                      int64
}

func (q *Queries) SetV2UploadFinalizing(ctx context.Context, arg SetV2UploadFinalizingParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, setV2UploadFinalizing,
		arg.FileKeyRecord,
		arg.ManifestRecord,
		arg.ManifestSignature,
		arg.CurrentVersionRecord,
		arg.CurrentVersionSignature,
		arg.ID,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NodePublicID,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.ParentEnvelope,
		&i.ParentEnvelopeSignature,
		&i.FileKeyRecord,
		&i.ManifestRecord,
		&i.ManifestSignature,
		&i.CurrentVersionRecord,
		&i.CurrentVersionSignature,
	)
	return i, err
}
