// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceUploadOffset = `-- name: AdvanceUploadOffset :one
UPDATE upload_sessions
SET upload_offset = $1,
    state = CASE WHEN $1 = declared_size THEN 'uploaded' ELSE 'uploading' END,
    updated_at = now()
WHERE id = $2 AND upload_offset = $3
  AND state IN ('created', 'uploading')
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at
`

type AdvanceUploadOffsetParams struct {
	NextOffset    int64
	ID            int64
	CurrentOffset int64
}

func (q *Queries) AdvanceUploadOffset(ctx context.Context, arg AdvanceUploadOffsetParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, advanceUploadOffset, arg.NextOffset, arg.ID, arg.CurrentOffset)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelUploadSession = `-- name: CancelUploadSession :one
UPDATE upload_sessions
SET state = 'cancelled', updated_at = now()
WHERE public_id = $1 AND owner_id = $2
  AND state IN ('created', 'uploading', 'uploaded', 'failed')
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at
`

type CancelUploadSessionParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) CancelUploadSession(ctx context.Context, arg CancelUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, cancelUploadSession, arg.PublicID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeUploadSession = `-- name: CompleteUploadSession :exec
UPDATE upload_sessions
SET state = 'completed', published_node_id = $2, published_version_id = $3,
    completed_at = now(), updated_at = now(), failure_code = NULL, failure_message = NULL
WHERE id = $1 AND state = 'finalizing'
`

type CompleteUploadSessionParams struct {
	ID                 int64
	PublishedNodeID    pgtype.Int8
	PublishedVersionID pgtype.Int8
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) error {
	_, err := q.db.Exec(ctx, completeUploadSession, arg.ID, arg.PublishedNodeID, arg.PublishedVersionID)
	return err
}

const createUploadFileNode = `-- name: CreateUploadFileNode :one
INSERT INTO nodes (public_id, library_id, parent_id, kind, name, encrypted_name, name_token)
VALUES ($1, $2, $3, 'file', $4, $5, $6)
RETURNING id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at
`

type CreateUploadFileNodeParams struct {
	PublicID      string
	LibraryID     int64
	ParentID      pgtype.Int8
	Name          pgtype.Text
	EncryptedName []byte
	NameToken     []byte
}

func (q *Queries) CreateUploadFileNode(ctx context.Context, arg CreateUploadFileNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createUploadFileNode,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (
    public_id, owner_id, library_id, parent_id, target_node_id, expected_revision,
    name, encrypted_name, name_token, declared_size, staging_key, destination_key,
    state, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    'created', $13
)
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at
`

type CreateUploadSessionParams struct {
	PublicID         string
	OwnerID          int64
	LibraryID        int64
	ParentID         int64
	TargetNodeID     pgtype.Int8
	ExpectedRevision pgtype.Int8
	Name             pgtype.Text
	EncryptedName    []byte
	NameToken        []byte
	DeclaredSize     int64
	StagingKey       string
	DestinationKey   string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.PublicID,
		arg.OwnerID,
		arg.LibraryID,
		arg.ParentID,
		arg.TargetNodeID,
		arg.ExpectedRevision,
		arg.Name,
		arg.EncryptedName,
		arg.NameToken,
		arg.DeclaredSize,
		arg.StagingKey,
		arg.DestinationKey,
		arg.ExpiresAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const expireUploadSessions = `-- name: ExpireUploadSessions :many
UPDATE upload_sessions
SET state = 'expired', updated_at = now()
WHERE expires_at < now() AND state IN ('created', 'uploading', 'uploaded', 'failed')
RETURNING staging_key
`

func (q *Queries) ExpireUploadSessions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, expireUploadSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var staging_key string
		if err := rows.Scan(&staging_key); err != nil {
			return nil, err
		}
		items = append(items, staging_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failUploadSession = `-- name: FailUploadSession :exec
UPDATE upload_sessions
SET state = $2, failure_code = $3, failure_message = $4, updated_at = now()
WHERE id = $1 AND state = 'finalizing'
`

type FailUploadSessionParams struct {
	ID             int64
	State          string
	FailureCode    pgtype.Text
	FailureMessage pgtype.Text
}

func (q *Queries) FailUploadSession(ctx context.Context, arg FailUploadSessionParams) error {
	_, err := q.db.Exec(ctx, failUploadSession,
		arg.ID,
		arg.State,
		arg.FailureCode,
		arg.FailureMessage,
	)
	return err
}

const getFileVersionByID = `-- name: GetFileVersionByID :one
SELECT id, public_id, node_id, library_id, ordinal, blob_id, size_bytes, content_sha256, restored_from_version_id, created_at FROM file_versions WHERE id = $1
`

func (q *Queries) GetFileVersionByID(ctx context.Context, id int64) (FileVersion, error) {
	row := q.db.QueryRow(ctx, getFileVersionByID, id)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.NodeID,
		&i.LibraryID,
		&i.Ordinal,
		&i.BlobID,
		&i.SizeBytes,
		&i.ContentSha256,
		&i.RestoredFromVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishedUploadIDs = `-- name: GetPublishedUploadIDs :one
SELECT n.public_id AS node_public_id, v.public_id AS version_public_id
FROM upload_sessions u
JOIN nodes n ON n.id = u.published_node_id
JOIN file_versions v ON v.id = u.published_version_id
WHERE u.id = $1
`

type GetPublishedUploadIDsRow struct {
	NodePublicID    string
	VersionPublicID string
}

func (q *Queries) GetPublishedUploadIDs(ctx context.Context, id int64) (GetPublishedUploadIDsRow, error) {
	row := q.db.QueryRow(ctx, getPublishedUploadIDs, id)
	var i GetPublishedUploadIDsRow
	err := row.Scan(&i.NodePublicID, &i.VersionPublicID)
	return i, err
}

const getUploadPublication = `-- name: GetUploadPublication :one
SELECT u.id, u.public_id, u.owner_id, u.library_id, u.parent_id, u.target_node_id, u.expected_revision, u.name, u.encrypted_name, u.name_token, u.declared_size, u.upload_offset, u.staging_key, u.destination_key, u.state, u.dedup_fingerprint, u.encryption_format, u.encrypted_file_key, u.published_node_id, u.published_version_id, u.failure_code, u.failure_message, u.expires_at, u.created_at, u.updated_at, u.completed_at, l.public_id AS library_public_id, l.backend_id, l.encryption_mode,
       b.public_id AS backend_public_id
FROM upload_sessions u
JOIN libraries l ON l.id = u.library_id
JOIN storage_backends b ON b.id = l.backend_id
WHERE u.id = $1
`

type GetUploadPublicationRow struct {
	ID                 int64
	PublicID           string
	OwnerID            int64
	LibraryID          int64
	ParentID           int64
	TargetNodeID       pgtype.Int8
	ExpectedRevision   pgtype.Int8
	Name               pgtype.Text
	EncryptedName      []byte
	NameToken          []byte
	DeclaredSize       int64
	UploadOffset       int64
	StagingKey         string
	DestinationKey     string
	State              string
	DedupFingerprint   []byte
	EncryptionFormat   pgtype.Text
	EncryptedFileKey   []byte
	PublishedNodeID    pgtype.Int8
	PublishedVersionID pgtype.Int8
	FailureCode        pgtype.Text
	FailureMessage     pgtype.Text
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	LibraryPublicID    string
	BackendID          int64
	EncryptionMode     string
	BackendPublicID    string
}

func (q *Queries) GetUploadPublication(ctx context.Context, id int64) (GetUploadPublicationRow, error) {
	row := q.db.QueryRow(ctx, getUploadPublication, id)
	var i GetUploadPublicationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.LibraryPublicID,
		&i.BackendID,
		&i.EncryptionMode,
		&i.BackendPublicID,
	)
	return i, err
}

const getUploadSessionByPublicIDAndOwner = `-- name: GetUploadSessionByPublicIDAndOwner :one
SELECT u.id, u.public_id, u.owner_id, u.library_id, u.parent_id, u.target_node_id, u.expected_revision, u.name, u.encrypted_name, u.name_token, u.declared_size, u.upload_offset, u.staging_key, u.destination_key, u.state, u.dedup_fingerprint, u.encryption_format, u.encrypted_file_key, u.published_node_id, u.published_version_id, u.failure_code, u.failure_message, u.expires_at, u.created_at, u.updated_at, u.completed_at
FROM upload_sessions u
WHERE u.public_id = $1 AND u.owner_id = $2
`

type GetUploadSessionByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

func (q *Queries) GetUploadSessionByPublicIDAndOwner(ctx context.Context, arg GetUploadSessionByPublicIDAndOwnerParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUploadSessionForUpdate = `-- name: GetUploadSessionForUpdate :one
SELECT id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at FROM upload_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, id int64) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const lockLibraryByID = `-- name: LockLibraryByID :exec
SELECT id FROM libraries WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockLibraryByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockLibraryByID, id)
	return err
}

const lockLibraryForUpload = `-- name: LockLibraryForUpload :one
SELECT l.id, l.public_id, l.owner_id, l.backend_id, l.root_node_id, l.name, l.encryption_mode, l.key_envelope, l.created_at, l.updated_at, b.public_id AS backend_public_id, b.name AS backend_name
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
WHERE l.public_id = $1 AND l.owner_id = $2 AND b.enabled = true
FOR UPDATE OF l
`

type LockLibraryForUploadParams struct {
	PublicID string
	OwnerID  int64
}

type LockLibraryForUploadRow struct {
	ID              int64
	PublicID        string
	OwnerID         int64
	BackendID       int64
	RootNodeID      int64
	Name            string
	EncryptionMode  string
	KeyEnvelope     []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	BackendPublicID string
	BackendName     string
}

func (q *Queries) LockLibraryForUpload(ctx context.Context, arg LockLibraryForUploadParams) (LockLibraryForUploadRow, error) {
	row := q.db.QueryRow(ctx, lockLibraryForUpload, arg.PublicID, arg.OwnerID)
	var i LockLibraryForUploadRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.BackendID,
		&i.RootNodeID,
		&i.Name,
		&i.EncryptionMode,
		&i.KeyEnvelope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackendPublicID,
		&i.BackendName,
	)
	return i, err
}

const lockNodeForPublication = `-- name: LockNodeForPublication :one
SELECT id, public_id, library_id, parent_id, kind, name, encrypted_name, name_token, current_version_id, revision, trashed_at, created_at, updated_at FROM nodes WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockNodeForPublication(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRow(ctx, lockNodeForPublication, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUploadAdmission = `-- name: LockUploadAdmission :exec
SELECT pg_advisory_xact_lock(1937011297)
`

func (q *Queries) LockUploadAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUploadAdmission)
	return err
}

const markUploadFailed = `-- name: MarkUploadFailed :exec
UPDATE upload_sessions
SET state = 'failed', failure_code = $2, failure_message = $3, updated_at = now()
WHERE id = $1 AND state IN ('created', 'uploading', 'uploaded', 'finalizing')
`

type MarkUploadFailedParams struct {
	ID             int64
	FailureCode    pgtype.Text
	FailureMessage pgtype.Text
}

func (q *Queries) MarkUploadFailed(ctx context.Context, arg MarkUploadFailedParams) error {
	_, err := q.db.Exec(ctx, markUploadFailed, arg.ID, arg.FailureCode, arg.FailureMessage)
	return err
}

const nextFileVersionOrdinal = `-- name: NextFileVersionOrdinal :one
SELECT coalesce(max(ordinal), 0)::bigint + 1
FROM file_versions WHERE node_id = $1
`

func (q *Queries) NextFileVersionOrdinal(ctx context.Context, nodeID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextFileVersionOrdinal, nodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setPlainUploadFinalizing = `-- name: SetPlainUploadFinalizing :one
UPDATE upload_sessions
SET state = 'finalizing', failure_code = NULL, failure_message = NULL, updated_at = now()
WHERE id = $1 AND state = 'uploaded' AND upload_offset = declared_size
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at
`

func (q *Queries) SetPlainUploadFinalizing(ctx context.Context, id int64) (UploadSession, error) {
	row := q.db.QueryRow(ctx, setPlainUploadFinalizing, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setUploadFinalizing = `-- name: SetUploadFinalizing :one
UPDATE upload_sessions
SET dedup_fingerprint = $1,
    encryption_format = $2,
    encrypted_file_key = $3,
    state = 'finalizing', failure_code = NULL, failure_message = NULL, updated_at = now()
WHERE id = $4 AND state = 'uploaded' AND upload_offset = declared_size
RETURNING id, public_id, owner_id, library_id, parent_id, target_node_id, expected_revision, name, encrypted_name, name_token, declared_size, upload_offset, staging_key, destination_key, state, dedup_fingerprint, encryption_format, encrypted_file_key, published_node_id, published_version_id, failure_code, failure_message, expires_at, created_at, updated_at, completed_at
`

type SetUploadFinalizingParams struct {
	DedupFingerprint []byte
	EncryptionFormat pgtype.Text
	EncryptedFileKey []byte
	ID               int64
}

func (q *Queries) SetUploadFinalizing(ctx context.Context, arg SetUploadFinalizingParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, setUploadFinalizing,
		arg.DedupFingerprint,
		arg.EncryptionFormat,
		arg.EncryptedFileKey,
		arg.ID,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.LibraryID,
		&i.ParentID,
		&i.TargetNodeID,
		&i.ExpectedRevision,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.DeclaredSize,
		&i.UploadOffset,
		&i.StagingKey,
		&i.DestinationKey,
		&i.State,
		&i.DedupFingerprint,
		&i.EncryptionFormat,
		&i.EncryptedFileKey,
		&i.PublishedNodeID,
		&i.PublishedVersionID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setUploadFingerprint = `-- name: SetUploadFingerprint :exec
UPDATE upload_sessions SET dedup_fingerprint = $2, updated_at = now() WHERE id = $1
`

type SetUploadFingerprintParams struct {
	ID               int64
	DedupFingerprint []byte
}

func (q *Queries) SetUploadFingerprint(ctx context.Context, arg SetUploadFingerprintParams) error {
	_, err := q.db.Exec(ctx, setUploadFingerprint, arg.ID, arg.DedupFingerprint)
	return err
}

const setZeroLengthUploadReady = `-- name: SetZeroLengthUploadReady :exec
UPDATE upload_sessions SET state = 'uploaded', updated_at = now()
WHERE id = $1 AND declared_size = 0 AND state = 'created'
`

func (q *Queries) SetZeroLengthUploadReady(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setZeroLengthUploadReady, id)
	return err
}

const sumAllUploadReservations = `-- name: SumAllUploadReservations :one
SELECT coalesce(sum(declared_size), 0)::bigint
FROM upload_sessions
WHERE state IN ('created', 'uploading', 'uploaded', 'finalizing', 'failed')
`

func (q *Queries) SumAllUploadReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumAllUploadReservations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateNodeCurrentVersion = `-- name: UpdateNodeCurrentVersion :exec
UPDATE nodes
SET current_version_id = $2, revision = revision + 1, updated_at = now()
WHERE id = $1
`

type UpdateNodeCurrentVersionParams struct {
	ID               int64
	CurrentVersionID pgtype.Int8
}

func (q *Queries) UpdateNodeCurrentVersion(ctx context.Context, arg UpdateNodeCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, updateNodeCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}
