// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_deletion.sql

package db

import (
	"context"
)

const clearUserCurrentVersions = `-- name: ClearUserCurrentVersions :exec
UPDATE nodes
SET current_version_id = NULL
WHERE library_id IN (SELECT id FROM libraries WHERE owner_id = $1)
`

func (q *Queries) ClearUserCurrentVersions(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, clearUserCurrentVersions, ownerID)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserBlobLocations = `-- name: DeleteUserBlobLocations :exec
DELETE FROM blob_locations
WHERE library_id IN (SELECT id FROM libraries WHERE owner_id = $1)
`

func (q *Queries) DeleteUserBlobLocations(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteUserBlobLocations, ownerID)
	return err
}

const deleteUserBlobs = `-- name: DeleteUserBlobs :exec
DELETE FROM blobs
WHERE library_id IN (SELECT id FROM libraries WHERE owner_id = $1)
`

func (q *Queries) DeleteUserBlobs(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteUserBlobs, ownerID)
	return err
}

const deleteUserFileVersions = `-- name: DeleteUserFileVersions :exec
DELETE FROM file_versions
WHERE library_id IN (SELECT id FROM libraries WHERE owner_id = $1)
`

func (q *Queries) DeleteUserFileVersions(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFileVersions, ownerID)
	return err
}

const deleteUserLeafNodes = `-- name: DeleteUserLeafNodes :many
WITH leaves AS (
    SELECT n.id
    FROM nodes n
    JOIN libraries l ON l.id = n.library_id
    WHERE l.owner_id = $1
      AND n.id <> l.root_node_id
      AND NOT EXISTS (SELECT 1 FROM nodes child WHERE child.parent_id = n.id)
)
DELETE FROM nodes
WHERE id IN (SELECT id FROM leaves)
RETURNING id
`

func (q *Queries) DeleteUserLeafNodes(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteUserLeafNodes, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserLibraries = `-- name: DeleteUserLibraries :execrows
DELETE FROM libraries WHERE owner_id = $1
`

func (q *Queries) DeleteUserLibraries(ctx context.Context, ownerID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserLibraries, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserUploadSessions = `-- name: DeleteUserUploadSessions :exec
DELETE FROM upload_sessions WHERE owner_id = $1
`

func (q *Queries) DeleteUserUploadSessions(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteUserUploadSessions, ownerID)
	return err
}

const listUserBlobDeletionTargets = `-- name: ListUserBlobDeletionTargets :many
SELECT sb.public_id AS backend_public_id, bl.object_key
FROM blob_locations bl
JOIN libraries l ON l.id = bl.library_id
JOIN storage_backends sb ON sb.id = bl.backend_id
WHERE l.owner_id = $1
`

type ListUserBlobDeletionTargetsRow struct {
	BackendPublicID string
	ObjectKey       string
}

func (q *Queries) ListUserBlobDeletionTargets(ctx context.Context, ownerID int64) ([]ListUserBlobDeletionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listUserBlobDeletionTargets, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBlobDeletionTargetsRow
	for rows.Next() {
		var i ListUserBlobDeletionTargetsRow
		if err := rows.Scan(&i.BackendPublicID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUploadDeletionTargets = `-- name: ListUserUploadDeletionTargets :many
SELECT sb.public_id AS backend_public_id, u.destination_key, u.staging_key
FROM upload_sessions u
JOIN libraries l ON l.id = u.library_id
JOIN storage_backends sb ON sb.id = l.backend_id
WHERE u.owner_id = $1
`

type ListUserUploadDeletionTargetsRow struct {
	BackendPublicID string
	DestinationKey  string
	StagingKey      string
}

func (q *Queries) ListUserUploadDeletionTargets(ctx context.Context, ownerID int64) ([]ListUserUploadDeletionTargetsRow, error) {
	rows, err := q.db.Query(ctx, listUserUploadDeletionTargets, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserUploadDeletionTargetsRow
	for rows.Next() {
		var i ListUserUploadDeletionTargetsRow
		if err := rows.Scan(&i.BackendPublicID, &i.DestinationKey, &i.StagingKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserLibraries = `-- name: LockUserLibraries :many
SELECT id FROM libraries WHERE owner_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockUserLibraries(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockUserLibraries, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserUploadSessions = `-- name: LockUserUploadSessions :many
SELECT id FROM upload_sessions WHERE owner_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockUserUploadSessions(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockUserUploadSessions, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
