// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeKeyEnvelope = `-- name: CreateNodeKeyEnvelope :exec
INSERT INTO node_key_envelopes (
    child_node_id, parent_node_id, library_id, child_epoch, parent_epoch, generation, ciphertext, owner_signature
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateNodeKeyEnvelopeParams struct {
	ChildNodeID    int64
	ParentNodeID   int64
	LibraryID      int64
	ChildEpoch     int64
	ParentEpoch    int64
	Generation     int64
	Ciphertext     []byte
	OwnerSignature []byte
}

func (q *Queries) CreateNodeKeyEnvelope(ctx context.Context, arg CreateNodeKeyEnvelopeParams) error {
	_, err := q.db.Exec(ctx, createNodeKeyEnvelope,
		arg.ChildNodeID,
		arg.ParentNodeID,
		arg.LibraryID,
		arg.ChildEpoch,
		arg.ParentEpoch,
		arg.Generation,
		arg.Ciphertext,
		arg.OwnerSignature,
	)
	return err
}

const createV2ChildNode = `-- name: CreateV2ChildNode :one
INSERT INTO nodes (
    public_id, library_id, parent_id, kind, name_token, encrypted_metadata, metadata_signature,
    key_epoch, metadata_revision
) VALUES ($1, $2, $3, $4, $5, $6, $7, 1, 1)
RETURNING id
`

type CreateV2ChildNodeParams struct {
	PublicID          string
	LibraryID         int64
	ParentID          pgtype.Int8
	Kind              string
	NameToken         []byte
	EncryptedMetadata []byte
	MetadataSignature []byte
}

func (q *Queries) CreateV2ChildNode(ctx context.Context, arg CreateV2ChildNodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createV2ChildNode,
		arg.PublicID,
		arg.LibraryID,
		arg.ParentID,
		arg.Kind,
		arg.NameToken,
		arg.EncryptedMetadata,
		arg.MetadataSignature,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createV2Library = `-- name: CreateV2Library :exec
INSERT INTO libraries (
    id, public_id, owner_id, backend_id, root_node_id, encryption_mode, encryption_format,
    encrypted_root_metadata, owner_root_envelope
)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, $4, $5, 'e2ee', 'v2', $6, $7)
`

type CreateV2LibraryParams struct {
	ID                    int64
	PublicID              string
	OwnerID               int64
	BackendID             int64
	RootNodeID            int64
	EncryptedRootMetadata []byte
	OwnerRootEnvelope     []byte
}

func (q *Queries) CreateV2Library(ctx context.Context, arg CreateV2LibraryParams) error {
	_, err := q.db.Exec(ctx, createV2Library,
		arg.ID,
		arg.PublicID,
		arg.OwnerID,
		arg.BackendID,
		arg.RootNodeID,
		arg.EncryptedRootMetadata,
		arg.OwnerRootEnvelope,
	)
	return err
}

const createV2RootNode = `-- name: CreateV2RootNode :exec
INSERT INTO nodes (id, public_id, library_id, kind, key_epoch, metadata_revision, metadata_signature)
OVERRIDING SYSTEM VALUE
VALUES ($1, $2, $3, 'folder', 1, 1, $4)
`

type CreateV2RootNodeParams struct {
	ID                int64
	PublicID          string
	LibraryID         int64
	MetadataSignature []byte
}

func (q *Queries) CreateV2RootNode(ctx context.Context, arg CreateV2RootNodeParams) error {
	_, err := q.db.Exec(ctx, createV2RootNode,
		arg.ID,
		arg.PublicID,
		arg.LibraryID,
		arg.MetadataSignature,
	)
	return err
}

const getV2LibraryByPublicIDAndOwner = `-- name: GetV2LibraryByPublicIDAndOwner :one
SELECT l.id, l.public_id, l.encrypted_root_metadata, l.owner_root_envelope, l.created_at, l.updated_at,
       b.public_id AS backend_public_id, b.name AS backend_name, b.type AS backend_type,
       root.id AS root_node_id, root.public_id AS root_node_public_id, root.key_epoch AS root_key_epoch,
       root.metadata_revision AS root_metadata_revision, root.metadata_signature AS root_metadata_signature
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
JOIN nodes root ON root.id = l.root_node_id
WHERE l.public_id = $1 AND l.owner_id = $2 AND l.encryption_format = 'v2'
`

type GetV2LibraryByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

type GetV2LibraryByPublicIDAndOwnerRow struct {
	ID                    int64
	PublicID              string
	EncryptedRootMetadata []byte
	OwnerRootEnvelope     []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	BackendPublicID       string
	BackendName           string
	BackendType           string
	RootNodeID            int64
	RootNodePublicID      string
	RootKeyEpoch          int64
	RootMetadataRevision  int64
	RootMetadataSignature []byte
}

func (q *Queries) GetV2LibraryByPublicIDAndOwner(ctx context.Context, arg GetV2LibraryByPublicIDAndOwnerParams) (GetV2LibraryByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getV2LibraryByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i GetV2LibraryByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.EncryptedRootMetadata,
		&i.OwnerRootEnvelope,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BackendPublicID,
		&i.BackendName,
		&i.BackendType,
		&i.RootNodeID,
		&i.RootNodePublicID,
		&i.RootKeyEpoch,
		&i.RootMetadataRevision,
		&i.RootMetadataSignature,
	)
	return i, err
}

const getV2NodeByPublicIDAndOwner = `-- name: GetV2NodeByPublicIDAndOwner :one
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at, n.key_epoch, n.metadata_revision, n.encrypted_metadata, n.metadata_signature, n.current_version_pointer, n.current_version_signature, n.visible_encryption_generation, l.public_id AS library_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.public_id = $1 AND l.owner_id = $2 AND l.encryption_format = 'v2'
`

type GetV2NodeByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

type GetV2NodeByPublicIDAndOwnerRow struct {
	ID                          int64
	PublicID                    string
	LibraryID                   int64
	ParentID                    pgtype.Int8
	Kind                        string
	Name                        pgtype.Text
	EncryptedName               []byte
	NameToken                   []byte
	CurrentVersionID            pgtype.Int8
	Revision                    int64
	TrashedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	KeyEpoch                    int64
	MetadataRevision            int64
	EncryptedMetadata           []byte
	MetadataSignature           []byte
	CurrentVersionPointer       []byte
	CurrentVersionSignature     []byte
	VisibleEncryptionGeneration int64
	LibraryPublicID             string
}

func (q *Queries) GetV2NodeByPublicIDAndOwner(ctx context.Context, arg GetV2NodeByPublicIDAndOwnerParams) (GetV2NodeByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getV2NodeByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i GetV2NodeByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
		&i.LibraryPublicID,
	)
	return i, err
}

const getV2NodeView = `-- name: GetV2NodeView :one
SELECT n.id, n.public_id, n.kind, n.name_token, n.encrypted_metadata, n.metadata_signature, n.key_epoch,
       n.metadata_revision, n.revision, n.current_version_pointer, n.current_version_signature,
       n.created_at, n.updated_at, parent.public_id AS parent_public_id,
       e.ciphertext AS parent_envelope, e.owner_signature AS parent_envelope_signature
FROM nodes n
JOIN nodes parent ON parent.id = n.parent_id
JOIN node_key_envelopes e ON e.child_node_id = n.id AND e.parent_node_id = n.parent_id
    AND e.child_epoch = n.key_epoch AND e.generation = n.visible_encryption_generation
WHERE n.id = $1
`

type GetV2NodeViewRow struct {
	ID                      int64
	PublicID                string
	Kind                    string
	NameToken               []byte
	EncryptedMetadata       []byte
	MetadataSignature       []byte
	KeyEpoch                int64
	MetadataRevision        int64
	Revision                int64
	CurrentVersionPointer   []byte
	CurrentVersionSignature []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	ParentPublicID          string
	ParentEnvelope          []byte
	ParentEnvelopeSignature []byte
}

func (q *Queries) GetV2NodeView(ctx context.Context, id int64) (GetV2NodeViewRow, error) {
	row := q.db.QueryRow(ctx, getV2NodeView, id)
	var i GetV2NodeViewRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Kind,
		&i.NameToken,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.Revision,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentPublicID,
		&i.ParentEnvelope,
		&i.ParentEnvelopeSignature,
	)
	return i, err
}

const listV2ChildNodes = `-- name: ListV2ChildNodes :many
SELECT n.id, n.public_id, n.kind, n.name_token, n.encrypted_metadata, n.metadata_signature, n.key_epoch,
       n.metadata_revision, n.revision, n.current_version_pointer, n.current_version_signature,
       n.created_at, n.updated_at,
       e.ciphertext AS parent_envelope, e.owner_signature AS parent_envelope_signature
FROM nodes n
JOIN node_key_envelopes e ON e.child_node_id = n.id AND e.parent_node_id = n.parent_id
    AND e.child_epoch = n.key_epoch AND e.generation = n.visible_encryption_generation
WHERE n.library_id = $1 AND n.parent_id = $2
  AND n.trashed_at IS NULL AND n.id > $3
ORDER BY n.id
LIMIT $4
`

type ListV2ChildNodesParams struct {
	LibraryID int64
	ParentID  pgtype.Int8
	AfterID   int64
	PageLimit int32
}

type ListV2ChildNodesRow struct {
	ID                      int64
	PublicID                string
	Kind                    string
	NameToken               []byte
	EncryptedMetadata       []byte
	MetadataSignature       []byte
	KeyEpoch                int64
	MetadataRevision        int64
	Revision                int64
	CurrentVersionPointer   []byte
	CurrentVersionSignature []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	ParentEnvelope          []byte
	ParentEnvelopeSignature []byte
}

func (q *Queries) ListV2ChildNodes(ctx context.Context, arg ListV2ChildNodesParams) ([]ListV2ChildNodesRow, error) {
	rows, err := q.db.Query(ctx, listV2ChildNodes,
		arg.LibraryID,
		arg.ParentID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListV2ChildNodesRow
	for rows.Next() {
		var i ListV2ChildNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Kind,
			&i.NameToken,
			&i.EncryptedMetadata,
			&i.MetadataSignature,
			&i.KeyEpoch,
			&i.MetadataRevision,
			&i.Revision,
			&i.CurrentVersionPointer,
			&i.CurrentVersionSignature,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentEnvelope,
			&i.ParentEnvelopeSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listV2LibrariesByOwner = `-- name: ListV2LibrariesByOwner :many
SELECT l.public_id, l.encrypted_root_metadata, l.owner_root_envelope, l.created_at, l.updated_at,
       b.public_id AS backend_public_id, b.name AS backend_name, b.type AS backend_type,
       root.public_id AS root_node_public_id, root.key_epoch AS root_key_epoch,
       root.metadata_revision AS root_metadata_revision, root.metadata_signature AS root_metadata_signature
FROM libraries l
JOIN storage_backends b ON b.id = l.backend_id
JOIN nodes root ON root.id = l.root_node_id
WHERE l.owner_id = $1 AND l.encryption_format = 'v2'
ORDER BY l.id
`

type ListV2LibrariesByOwnerRow struct {
	PublicID              string
	EncryptedRootMetadata []byte
	OwnerRootEnvelope     []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	BackendPublicID       string
	BackendName           string
	BackendType           string
	RootNodePublicID      string
	RootKeyEpoch          int64
	RootMetadataRevision  int64
	RootMetadataSignature []byte
}

func (q *Queries) ListV2LibrariesByOwner(ctx context.Context, ownerID int64) ([]ListV2LibrariesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listV2LibrariesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListV2LibrariesByOwnerRow
	for rows.Next() {
		var i ListV2LibrariesByOwnerRow
		if err := rows.Scan(
			&i.PublicID,
			&i.EncryptedRootMetadata,
			&i.OwnerRootEnvelope,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BackendPublicID,
			&i.BackendName,
			&i.BackendType,
			&i.RootNodePublicID,
			&i.RootKeyEpoch,
			&i.RootMetadataRevision,
			&i.RootMetadataSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockV2Library = `-- name: LockV2Library :one
SELECT l.id, root.id AS root_node_id, root.public_id AS root_node_public_id,
       root.key_epoch AS root_key_epoch, root.metadata_revision AS root_metadata_revision
FROM libraries l
JOIN nodes root ON root.id = l.root_node_id
WHERE l.public_id = $1 AND l.owner_id = $2 AND l.encryption_format = 'v2'
FOR UPDATE OF l, root
`

type LockV2LibraryParams struct {
	PublicID string
	OwnerID  int64
}

type LockV2LibraryRow struct {
	ID                   int64
	RootNodeID           int64
	RootNodePublicID     string
	RootKeyEpoch         int64
	RootMetadataRevision int64
}

func (q *Queries) LockV2Library(ctx context.Context, arg LockV2LibraryParams) (LockV2LibraryRow, error) {
	row := q.db.QueryRow(ctx, lockV2Library, arg.PublicID, arg.OwnerID)
	var i LockV2LibraryRow
	err := row.Scan(
		&i.ID,
		&i.RootNodeID,
		&i.RootNodePublicID,
		&i.RootKeyEpoch,
		&i.RootMetadataRevision,
	)
	return i, err
}

const lockV2NodeByPublicIDAndOwner = `-- name: LockV2NodeByPublicIDAndOwner :one
SELECT n.id, n.public_id, n.library_id, n.parent_id, n.kind, n.name, n.encrypted_name, n.name_token, n.current_version_id, n.revision, n.trashed_at, n.created_at, n.updated_at, n.key_epoch, n.metadata_revision, n.encrypted_metadata, n.metadata_signature, n.current_version_pointer, n.current_version_signature, n.visible_encryption_generation, l.public_id AS library_public_id
FROM nodes n
JOIN libraries l ON l.id = n.library_id
WHERE n.public_id = $1 AND l.owner_id = $2 AND l.encryption_format = 'v2'
FOR UPDATE OF n
`

type LockV2NodeByPublicIDAndOwnerParams struct {
	PublicID string
	OwnerID  int64
}

type LockV2NodeByPublicIDAndOwnerRow struct {
	ID                          int64
	PublicID                    string
	LibraryID                   int64
	ParentID                    pgtype.Int8
	Kind                        string
	Name                        pgtype.Text
	EncryptedName               []byte
	NameToken                   []byte
	CurrentVersionID            pgtype.Int8
	Revision                    int64
	TrashedAt                   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	KeyEpoch                    int64
	MetadataRevision            int64
	EncryptedMetadata           []byte
	MetadataSignature           []byte
	CurrentVersionPointer       []byte
	CurrentVersionSignature     []byte
	VisibleEncryptionGeneration int64
	LibraryPublicID             string
}

func (q *Queries) LockV2NodeByPublicIDAndOwner(ctx context.Context, arg LockV2NodeByPublicIDAndOwnerParams) (LockV2NodeByPublicIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, lockV2NodeByPublicIDAndOwner, arg.PublicID, arg.OwnerID)
	var i LockV2NodeByPublicIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.LibraryID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.EncryptedName,
		&i.NameToken,
		&i.CurrentVersionID,
		&i.Revision,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KeyEpoch,
		&i.MetadataRevision,
		&i.EncryptedMetadata,
		&i.MetadataSignature,
		&i.CurrentVersionPointer,
		&i.CurrentVersionSignature,
		&i.VisibleEncryptionGeneration,
		&i.LibraryPublicID,
	)
	return i, err
}

const updateV2NodeMetadata = `-- name: UpdateV2NodeMetadata :exec
UPDATE nodes
SET encrypted_metadata = $1, metadata_signature = $2,
    metadata_revision = $3, name_token = $4, updated_at = now()
WHERE id = $5 AND parent_id IS NOT NULL AND trashed_at IS NULL
`

type UpdateV2NodeMetadataParams struct {
	EncryptedMetadata []byte
	MetadataSignature []byte
	MetadataRevision  int64
	NameToken         []byte
	ID                int64
}

func (q *Queries) UpdateV2NodeMetadata(ctx context.Context, arg UpdateV2NodeMetadataParams) error {
	_, err := q.db.Exec(ctx, updateV2NodeMetadata,
		arg.EncryptedMetadata,
		arg.MetadataSignature,
		arg.MetadataRevision,
		arg.NameToken,
		arg.ID,
	)
	return err
}

const updateV2RootMetadata = `-- name: UpdateV2RootMetadata :exec
UPDATE libraries SET encrypted_root_metadata = $2, updated_at = now()
WHERE id = $1 AND encryption_format = 'v2'
`

type UpdateV2RootMetadataParams struct {
	ID                    int64
	EncryptedRootMetadata []byte
}

func (q *Queries) UpdateV2RootMetadata(ctx context.Context, arg UpdateV2RootMetadataParams) error {
	_, err := q.db.Exec(ctx, updateV2RootMetadata, arg.ID, arg.EncryptedRootMetadata)
	return err
}

const updateV2RootMetadataSignature = `-- name: UpdateV2RootMetadataSignature :exec
UPDATE nodes SET metadata_revision = $2, metadata_signature = $3, updated_at = now()
WHERE id = $1 AND parent_id IS NULL
`

type UpdateV2RootMetadataSignatureParams struct {
	ID                int64
	MetadataRevision  int64
	MetadataSignature []byte
}

func (q *Queries) UpdateV2RootMetadataSignature(ctx context.Context, arg UpdateV2RootMetadataSignatureParams) error {
	_, err := q.db.Exec(ctx, updateV2RootMetadataSignature, arg.ID, arg.MetadataRevision, arg.MetadataSignature)
	return err
}
